/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasLogin;

import Modelo.LoginManager;
import Ventanas.MenuPrincipal;
import java.awt.*;
import javax.swing.*;
import java.io.IOException;
/**
 *
 * @author josea
 */
public class Login extends javax.swing.JFrame {
    
    private LoginManager manager = new LoginManager();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Recursos/tribal - Editado.png")).getImage());
        
        //llamar el metodo add
        addPlaceholderStyle(this.txtUsuario);;
        addPlaceholderStyle(this.pswContraseña);
    }
    
    //Metodos para cambiar place holders
    public void addPlaceholderStyle(JTextField textField) {
        Font fuente = textField.getFont();
        fuente = fuente.deriveFont(Font.ITALIC);
        textField.setFont(fuente);
        textField.setForeground(Color.gray); //Este es el color de la fuente que va a tommar primeramente
    }
    
    public void removePlaceholderStyle(JTextField textField) {
        Font fuente = textField.getFont();
        fuente = fuente.deriveFont(Font.PLAIN | Font.BOLD);
        textField.setFont(fuente);
        textField.setForeground(Color.black);//Este ya es el color que tomara al darle click en el
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        pswContraseña = new javax.swing.JPasswordField();
        btnAcceder = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnCrearUsuario = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnRecuperarDatos = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login (Inicio de Sesion)");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Gestor de la empresa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 350, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/azteca tec logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 230, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Azteca Tec fondo login(Editado).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Icono_Usuario.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(172, 6, 125, 128);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Login");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 140, 110, 50);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel6.setText("Ingresa tu Contraseña");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 290, 220, 20);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 350, 250, 10);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel7.setText("Ingresa tu nombre de usuario:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 200, 220, 20);

        txtUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtUsuario.setText("Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(10, 230, 350, 30);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(10, 263, 350, 10);

        pswContraseña.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        pswContraseña.setText("Contraseña");
        pswContraseña.setBorder(null);
        pswContraseña.setEchoChar('\u0000');
        pswContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswContraseñaFocusLost(evt);
            }
        });
        jPanel1.add(pswContraseña);
        pswContraseña.setBounds(10, 320, 250, 30);

        btnAcceder.setBackground(new java.awt.Color(0, 0, 102));
        btnAcceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/register_internet_direction_web_right_button_enter_arrow_login_icon_210831.png"))); // NOI18N
        btnAcceder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAcceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAccederMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccederMouseExited(evt);
            }
        });
        jPanel1.add(btnAcceder);
        btnAcceder.setBounds(20, 410, 70, 60);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setText("Recuperar Datos");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(210, 470, 110, 16);

        btnCrearUsuario.setBackground(new java.awt.Color(0, 0, 102));
        btnCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/contact_user_add_user_new_user_icon_250756.png"))); // NOI18N
        btnCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseExited(evt);
            }
        });
        jPanel1.add(btnCrearUsuario);
        btnCrearUsuario.setBounds(110, 410, 80, 60);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setText("Acceder");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 480, 60, 16);

        btnRecuperarDatos.setBackground(new java.awt.Color(0, 0, 102));
        btnRecuperarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/folder-restore_12344725.png"))); // NOI18N
        btnRecuperarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecuperarDatosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecuperarDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecuperarDatosMouseExited(evt);
            }
        });
        jPanel1.add(btnRecuperarDatos);
        btnRecuperarDatos.setBounds(220, 410, 90, 60);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setText("Crear Usuario");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(110, 480, 90, 16);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 450, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseEntered
        this.btnAcceder.setBackground(Color.green);
    }//GEN-LAST:event_btnAccederMouseEntered

    private void btnAccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseExited
        this.btnAcceder.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnAccederMouseExited

    private void btnAccederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseClicked
        String usuario = this.txtUsuario.getText();
        
        String contraseña = new String(this.pswContraseña.getPassword());
        
        if (usuario.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor llena todos los campos.", "ADVERTENCIA: Faltan Campos", 2);
            return;
        }
        

        
        try {
            if (manager.validarLogin(usuario, contraseña)) {
                JOptionPane.showMessageDialog(null, "Acceso exitoso. \n Bienvenido" + usuario, "Exito", 1);
                MenuPrincipal ventana2 = new MenuPrincipal();
                ventana2.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.", "ERROR", 0);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAccederMouseClicked

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (this.txtUsuario.getText().equals("Usuario")) {
            this.txtUsuario.setText(null);
            this.txtUsuario.requestFocus();
            //Llamar al metodo remove
            removePlaceholderStyle(this.txtUsuario);
        }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void pswContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswContraseñaFocusGained
        if (this.pswContraseña.getText().equals("Contraseña")) {
            this.pswContraseña.setText(null);
            this.pswContraseña.requestFocus();
            //Darle al password un formato de contraseña (EchoCjar)
            this.pswContraseña.setEchoChar('@');
            //Llamar al metodo remove
            removePlaceholderStyle(this.pswContraseña);
            
        }
    }//GEN-LAST:event_pswContraseñaFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (this.txtUsuario.getText().length() == 0) {
            //Llamar al metodo add cuando el cuadro de dialogo pierda el cursor
            addPlaceholderStyle(this.txtUsuario);
            this.txtUsuario.setText("Usuario");
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void pswContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswContraseñaFocusLost
        if (this.pswContraseña.getText().length() == 0) {
            //Llamar al metodo add
            addPlaceholderStyle(this.pswContraseña);
            this.pswContraseña.setText("Contraseña");
            this.pswContraseña.setEchoChar('\u0000');
            
        }
    }//GEN-LAST:event_pswContraseñaFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnCrearUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseEntered
        this.btnCrearUsuario.setBackground(Color.green);
    }//GEN-LAST:event_btnCrearUsuarioMouseEntered

    private void btnCrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseExited
        this.btnCrearUsuario.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnCrearUsuarioMouseExited

    private void btnCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseClicked
        CrearLogin ventana = new CrearLogin();
        ventana.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnCrearUsuarioMouseClicked

    private void btnRecuperarDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperarDatosMouseEntered
        this.btnRecuperarDatos.setBackground(Color.green);
    }//GEN-LAST:event_btnRecuperarDatosMouseEntered

    private void btnRecuperarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperarDatosMouseExited
        this.btnRecuperarDatos.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnRecuperarDatosMouseExited

    private void btnRecuperarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperarDatosMouseClicked
        RecuperarDatos ventana = new RecuperarDatos();
        ventana.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnRecuperarDatosMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnRecuperarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pswContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
