/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasLogin;

import Modelo.LoginManager;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author josea
 */
public class RecuperarDatos extends javax.swing.JFrame {
    
    private LoginManager manager = new LoginManager();

    /**
     * Creates new form RecuperarDatos
     */
    public RecuperarDatos() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Recursos/tribal - Editado.png")).getImage());
        
        addPlaceholderStyle(this.txtCorreo);
    }
    
    //Metodos para cambiar place holders
    public void addPlaceholderStyle(JTextField textField) {
        Font fuente = textField.getFont();
        fuente = fuente.deriveFont(Font.ITALIC);
        textField.setFont(fuente);
        textField.setForeground(Color.gray); //Este es el color de la fuente que va a tommar primeramente
    }
    
    public void removePlaceholderStyle(JTextField textField) {
        Font fuente = textField.getFont();
        fuente = fuente.deriveFont(Font.PLAIN | Font.BOLD);
        textField.setFont(fuente);
        textField.setForeground(Color.black);//Este ya es el color que tomara al darle click en el
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnRecuperar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkNoSoyRobot = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperar Datos");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/server_connection_data_server_database_storage_connection_icon_190644.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(130, 10, 80, 80);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Recuperar Datos");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 90, 180, 30);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("¿No eres un Robot?");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 300, 130, 20);

        txtCorreo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtCorreo.setText("Correo/email .com");
        txtCorreo.setBorder(null);
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        jPanel2.add(txtCorreo);
        txtCorreo.setBounds(20, 160, 260, 30);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(20, 190, 260, 30);

        btnRecuperar.setBackground(new java.awt.Color(0, 0, 102));
        btnRecuperar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/folder-restore_12344725.png"))); // NOI18N
        btnRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecuperarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecuperarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecuperarMouseExited(evt);
            }
        });
        jPanel2.add(btnRecuperar);
        btnRecuperar.setBounds(20, 220, 90, 60);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("Ingresa tu Correo Electronico:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 136, 190, 20);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("Recuperar Datos");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 240, 110, 20);

        chkNoSoyRobot.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        chkNoSoyRobot.setText("No soy Robot");
        jPanel2.add(chkNoSoyRobot);
        chkNoSoyRobot.setBounds(10, 330, 110, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 330, 420));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/azteca tec logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(79, 125, 235, 204);

        btnRegresar.setBackground(new java.awt.Color(204, 0, 204));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/exit_icon_125291.png"))); // NOI18N
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(0, 0, 60, 90);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 480));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Fondo para la ventana crear usuario.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 380, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        if (this.txtCorreo.getText().equals("Correo/email .com")) {
            this.txtCorreo.setText(null);
            this.txtCorreo.requestFocus();
            //Llamar al metodo remove
            removePlaceholderStyle(this.txtCorreo);
        }
    }//GEN-LAST:event_txtCorreoFocusGained

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        if (this.txtCorreo.getText().length() == 0) {
            //Llamar al metodo add cuando el cuadro de dialogo pierda el cursor
            addPlaceholderStyle(this.txtCorreo);
            this.txtCorreo.setText("Correo/email .com");
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void btnRecuperarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperarMouseEntered
        this.btnRecuperar.setBackground(Color.green);
    }//GEN-LAST:event_btnRecuperarMouseEntered

    private void btnRecuperarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperarMouseExited
        this.btnRecuperar.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnRecuperarMouseExited

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        this.btnRegresar.setBackground(Color.red);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        this.btnRegresar.setBackground(new Color(204, 0, 204));
    }//GEN-LAST:event_btnRegresarMouseExited

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnRecuperarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperarMouseClicked
        String correo = this.txtCorreo.getText();
        
        if (correo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa el Campo Correspondiente", "ADVERTENCIA: Campo Vacio", 2);
            this.txtCorreo.requestFocus();
            return;
        }
        
        //Validar antes No soy Robot
        if (!this.chkNoSoyRobot.isSelected()) {
            JOptionPane.showMessageDialog(null, "Por favor verefica que no eres un robot", "ADVERTENCIA: ERROR DE VERIFICACION", 0);
            return;
        }
        
        JOptionPane.showMessageDialog(null, "De acuerdo para verificar que realmente No eres un Robot \n Escribe un codigo de seguridad", "Codigo de verificacion", 1);
        Random random = new Random();
        int codigoValidacion = 1000 + random.nextInt(9000); //Codigo de 4 digitos
        String codigoIngresado = JOptionPane.showInputDialog(null, "Escriba el codigo de seguridad: \n" + codigoValidacion, "Validicacion", 1);
        
        if (codigoIngresado != null && codigoIngresado.equals(String.valueOf(codigoValidacion))) {
            JOptionPane.showMessageDialog(null, "Validacion Completada. Ahora puedes recuperar tu usuario y contraseña", "Exito", 1);
            try {
                String[] datos = manager.recuperarDatos(correo);
                if (datos != null) {
                    JOptionPane.showMessageDialog(null, "Usuario: " + datos[0] + "\nContraseña: " + datos[1], "Recuperacion de Datos", 1);
                } else {
                    JOptionPane.showMessageDialog(null, "Correo no encontrado", "ERROR: Correo No existente", 0);
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Codigo Incorrecto. Intenta de nuevo.", "ERROR", 0);
        }
    }//GEN-LAST:event_btnRecuperarMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        Login ventana = new Login();
        ventana.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox chkNoSoyRobot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
