/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

/**
 *
 * @author josea
 */
public class AcercaDe extends javax.swing.JPanel {

    /**
     * Creates new form AcercaDe
     */
    public AcercaDe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("\"Acerca De\" sobre el programa Gestor de Empresa \"Azteca Tec\"");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 780, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/abstract-blue-backgroundr.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Informacion resumida sobre el \"Gestor de Empresa.\"");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 180, 640, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel5.setText("Nombre del Programa: Gestor de Empresa \"Azteca Tec\"");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(6, 14, 640, 40);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel6.setText("Proposito del Programa: Gestiornar empleados, y hacer reportes sobre ellos para un mejor control");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 50, 1090, 40);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel7.setText("Fecha de Creacion de programa: 23/01/2025");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 90, 700, 40);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setText("Seccion Empleados:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 310, 1070, 20);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel9.setText("Version: 1.0.1");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(380, 130, 480, 40);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setText("1. Menu Principal: Cuenta con dos tres opciones \"Mi Gestor\", \"Instrucciones\" y \"Acerca de\" .");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 220, 1070, 20);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("1.5: Mi Gestor: Muestra reportes guardados, informacion del programa y algunos menus para trabajar.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 240, 1070, 20);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("1.8: Instrucciones: Da instrucciones especificas de como usar el programa correcta y abre el manual de usuario para mas informacion:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 260, 1070, 20);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setText("OJO: Existe un menu desplegable en la parte superior de color azul, dar click en el para abrirlo y cerrarlo.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 280, 1070, 20);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setText("2. Agregar Empleado: Agrega a un empleado con los datos correspondientes.    3. Lista de Empleados: Muestra a todos los empleados existentes.");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 340, 1070, 20);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel15.setText("8. Eleminar Reporte: Elemina el reporte de la lista.                             9. Menu \"Gestor de Empresa\" manda a otra seccion del programa.");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 460, 1070, 20);

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel16.setText("Seccion Reportes:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 400, 1070, 20);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel17.setText("4. Editar Empleado: Edita los datos del empleado.                     5. Borrar Empleado: Elemina empleados de la lista seleccionando su ID.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 360, 1070, 20);

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel18.setText("6. Generar Reportes: Genera Reportes de diferentes tipos.                      7. Lista de Reportes: Muestra todos los reportes existentes.");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 430, 1070, 20);

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel19.setText("Creador: Luis Davila Jose Angel");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 130, 480, 40);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
