/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

/**
 *
 * @author josea
 */
public class AcercaDeClientes extends javax.swing.JPanel {

    /**
     * Creates new form AcercaDeClientes
     */
    public AcercaDeClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("Acerca De (Gestor de Clientes).");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 26, 390, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/abstract-blue-backgroundr.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Seccion Reportes");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 340, 490, 20);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel4.setText("Nombre del Programa: Gestor de Clientes y Actividades \"Azteca Tec\".");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 710, 20);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel5.setText("Proposito: Gestionar y mantener un control en los datos de clientes y actividades en la empresa.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 30, 940, 20);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel6.setText("Version: 1.0.1");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 50, 630, 20);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setText("2.Lista Clientes: Ve en una tabla a todos clientes agregados.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 200, 490, 20);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("1. Menu Principal: Al igual que el primer gestor cuenta con \"Mi Gestor\", \"Instrucciones\"  y \"Acerca De\" con la misma funcion y proposito en 1er Gestor");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 120, 1080, 20);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Resumen sobre el Gestor de Clientes y Actividades.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 90, 490, 20);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setText("4. Borrar Cliente: Eliminada a un cliente de la lista seleccionando su ID.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(480, 200, 560, 20);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("y empleado correspondiente a esa actividad.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 270, 490, 20);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("3. Editar Cliente: Edita los datos de un cliente seleccionando su ID.");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(480, 180, 560, 20);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Seccion Clientes:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 150, 490, 20);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setText("2. Ve en una lista todos los reportes generados ya sea cliente o Act");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 380, 500, 20);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel15.setText("esa actividad.");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(510, 270, 580, 20);

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel16.setText("gradas a la empresa.");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 310, 490, 20);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel17.setText("3. Editar Actividad: Edita los datos de la actividad seleccionando el nombre de ");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(510, 250, 580, 20);

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel18.setText("1. Agregar Actividad: Agrega una actiividad a la empresa con cliente");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 250, 490, 20);

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel19.setText("actividad.");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(510, 310, 570, 20);

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel20.setText("2. Lista de Actividades: Ve en una tabla a todas la actividades agre-");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 290, 490, 20);

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel21.setText("4. Borrar Actividad: Elimina a una actividad seleccionando el nombre de esa");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(510, 290, 570, 20);

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("Seccion Actividades.");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 230, 490, 20);

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel23.setText("1. Agregar Cliente: Agrega clientes a la lista de la empresa");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(10, 180, 480, 20);

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel24.setText("3. Eliminar Reporte: Elimina un reporte de la lista.");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(510, 360, 500, 20);

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel25.setText("1. Generar Reporte: Genera tipos de reportes ya sea de cliente o Act.");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(10, 360, 500, 20);

        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel26.setText("Creador: Luis Davila Jose Angel.");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(10, 50, 940, 20);

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel27.setText("Creador: Luis Davila Jose Angel.");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(10, 50, 630, 20);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 480));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
