/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import Objeto.Actividades;
import ClasesUtilitarias.ArchivoUtilClientes;
import ClasesUtilitarias.ArchivoUtilEmpleados;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author josea
 */
public class AgregarActividad extends javax.swing.JPanel {

    /**
     * Creates new form AgregarActividad
     */
    public AgregarActividad() {
        initComponents();
        cargarIDsCliente();
        cargarIDsEmpleado();
    }
    
    
    private void cargarIDsCliente() {
        this.cboIDsCliente.addItem("-- Selecciona un ID --");
        List<String[]> datos =  ArchivoUtilClientes.leerArchivo("clientes.txt");
        
        for (String[] fila : datos) 
            this.cboIDsCliente.addItem(fila[0]);
    }
    
    private void cargarIDsEmpleado() {
        this.cboIDsEmpleado.addItem("-- Selecciona un ID --");
        List<String[]> datos = ArchivoUtilEmpleados.leerArchivo("empleados.txt");
        
        for (String[] fila : datos) 
            this.cboIDsEmpleado.addItem(fila[0]);
    }
    
    private void cargarDatosCliente() {
        if (this.cboIDsCliente.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Selecciona un ID en el Cliente,", "INFO", 1);
            configurarComponentesCliente();
            return;
        }
        
        actualizarComponentesClientes();
        
        String idSeleccionado = (String) this.cboIDsCliente.getSelectedItem();
        List<String[]> datos = ArchivoUtilClientes.leerArchivo("clientes.txt");
        for (String[] fila : datos) {
            if (fila[0].equals(idSeleccionado)) {
                this.txtApellidoCliente.setText(fila[1]);
                this.txtNombresCliente.setText(fila[2]);
                this.txtTelefonoCliente.setText(fila[4]);
                this.txtEstatusCliente.setText(fila[7]);
                if ("-- Inactivo --".equals(fila[7])) {
                    this.txtEstatusCliente.setForeground(Color.red);
                } else if ("-- Activo --".equals(fila[7])) {
                    this.txtEstatusCliente.setForeground(Color.green);
                } else {
                    this.txtEstatusCliente.setForeground(Color.black);
                }
                break;
            }
        }
    }
    
    private void cargarDatosEmpleado() {
        if (this.cboIDsEmpleado.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Selecciona un ID en el Empleado.", "INFO", 1);
            configurarComponentesEmpleado();
            return;
        }
        
        actualizarComponentesEmpleado();
        
        String idSeleccionado = (String) this.cboIDsEmpleado.getSelectedItem();
        List<String[]> datos = ArchivoUtilEmpleados.leerArchivo("empleados.txt");
        for (String[] fila : datos) {
            if (fila[0].equals(idSeleccionado)) {
                this.txtApellidoEmpleado.setText(fila[1]);
                this.txtNombresEmpleado.setText(fila[2]);
                this.txtCurp.setText(fila[5]);
                this.txtArea.setText(fila[9]);
                this.txtPuesto.setText(fila[10]);
                this.txtEstatusEmpleado.setText(fila[11]);
                if ("-- Inactivo --".equals(fila[11]) || "-- En Capacitacion --".equals(fila[11])) {
                    this.txtEstatusEmpleado.setForeground(Color.red);
                } else if ("-- Activo --".equals(fila[11])) {
                    this.txtEstatusEmpleado.setForeground(Color.green);
                } else {
                    this.txtEstatusEmpleado.setForeground(Color.black);
                }
                break;
            }
        }
    }
    
    
    private void limpiarCampos() {
        this.txtNumAct.setText(null);
        this.txtNomAct.setText(null);
        this.txtFechaInicio.setText(null);
        this.txtFechaFin.setText(null);
        this.cboEstatusAct.setSelectedItem("-- Selecciona un Estatus --");
        this.cboIDsCliente.setSelectedItem("-- Selecciona un ID --");
        this.cboIDsEmpleado.setSelectedItem("-- Selecciona un ID --");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomAct = new javax.swing.JTextField();
        txtNombresEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumAct = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cboIDsCliente = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtApellidoCliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNombresCliente = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtApellidoEmpleado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cboIDsEmpleado = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cboEstatusAct = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        txtPuesto = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtEstatusEmpleado = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtEstatusCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel1.setText("Fecha de Inicio:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(820, 80, 130, 30);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel4.setText("Datos del Empleado Responsable (Lider de la Actividad):");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 310, 590, 30);

        txtNomAct.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel1.add(txtNomAct);
        txtNomAct.setBounds(490, 80, 320, 30);

        txtNombresEmpleado.setEditable(false);
        txtNombresEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel1.add(txtNombresEmpleado);
        txtNombresEmpleado.setBounds(770, 340, 270, 30);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel6.setText("Nombre de la Actividad:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 80, 210, 30);

        txtNumAct.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel1.add(txtNumAct);
        txtNumAct.setBounds(160, 80, 140, 30);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel7.setText("Num de Actividad:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 80, 150, 30);

        txtFechaInicio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel1.add(txtFechaInicio);
        txtFechaInicio.setBounds(950, 80, 110, 30);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel8.setText("Estatus de la Actividad:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(260, 120, 200, 30);

        txtFechaFin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel1.add(txtFechaFin);
        txtFechaFin.setBounds(150, 120, 110, 30);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel9.setText("Nombres:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(710, 220, 100, 30);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel10.setText("Llena todos los espacios correspondientes para guardar la actividad:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 10, 830, 30);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 300, 1060, 10);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel5.setText("Datos de Actividad:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 50, 260, 30);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel11.setText("Telefono:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 260, 100, 30);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel12.setText("Nombres:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(680, 340, 100, 30);

        txtTelefonoCliente.setEditable(false);
        txtTelefonoCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel1.add(txtTelefonoCliente);
        txtTelefonoCliente.setBounds(90, 260, 240, 30);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel13.setText("ID del Empleado:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 340, 150, 30);

        txtCurp.setEditable(false);
        txtCurp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel1.add(txtCurp);
        txtCurp.setBounds(180, 380, 240, 30);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(10, 170, 1060, 10);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel14.setText("Datos del Cliente a Cargo:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 180, 260, 30);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel15.setText("ID Cliente de la Act:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 220, 170, 30);

        cboIDsCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIDsClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cboIDsCliente);
        cboIDsCliente.setBounds(170, 220, 220, 30);

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel16.setText("Estatus:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(410, 420, 80, 30);

        txtApellidoCliente.setEditable(false);
        txtApellidoCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel1.add(txtApellidoCliente);
        txtApellidoCliente.setBounds(470, 220, 240, 30);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel17.setText("Puesto:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 420, 70, 30);

        txtNombresCliente.setEditable(false);
        txtNombresCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel1.add(txtNombresCliente);
        txtNombresCliente.setBounds(800, 220, 270, 30);

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel18.setText("Apellido:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(370, 340, 100, 30);

        txtApellidoEmpleado.setEditable(false);
        txtApellidoEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel1.add(txtApellidoEmpleado);
        txtApellidoEmpleado.setBounds(440, 340, 240, 30);

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel19.setText("CURP del Empleado:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 380, 180, 30);

        cboIDsEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIDsEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(cboIDsEmpleado);
        cboIDsEmpleado.setBounds(140, 340, 220, 30);

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel20.setText("Area:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(430, 380, 70, 30);

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel21.setText("Fecha Aprox. Fin:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 120, 150, 30);

        cboEstatusAct.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        cboEstatusAct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona un Estatus --", "-- Planificacion --", "-- En Ejecucion --", "-- Pausada --", "-- Completada --", "-- Cancelada --", "-- En Revision --" }));
        jPanel1.add(cboEstatusAct);
        cboEstatusAct.setBounds(450, 120, 260, 30);

        btnGuardar.setBackground(new java.awt.Color(0, 0, 153));
        btnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(740, 420, 330, 60);

        txtPuesto.setEditable(false);
        txtPuesto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel1.add(txtPuesto);
        txtPuesto.setBounds(80, 420, 320, 30);

        txtArea.setEditable(false);
        txtArea.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel1.add(txtArea);
        txtArea.setBounds(480, 380, 320, 30);

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel22.setText("Apellido:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(400, 220, 100, 30);

        txtEstatusEmpleado.setEditable(false);
        txtEstatusEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel1.add(txtEstatusEmpleado);
        txtEstatusEmpleado.setBounds(480, 420, 210, 30);

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel23.setText("Estatus:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(340, 260, 80, 30);

        txtEstatusCliente.setEditable(false);
        txtEstatusCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel1.add(txtEstatusCliente);
        txtEstatusCliente.setBounds(410, 260, 160, 30);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 500));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/agregar act.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 10, 70, 70);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 26)); // NOI18N
        jLabel3.setText("Agregar Actividades.");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 30, 300, 30);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void cboIDsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIDsClienteActionPerformed
        cargarDatosCliente();
    }//GEN-LAST:event_cboIDsClienteActionPerformed

    private void cboIDsEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIDsEmpleadoActionPerformed
        cargarDatosEmpleado();
    }//GEN-LAST:event_cboIDsEmpleadoActionPerformed

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        this.btnGuardar.setBackground(Color.green);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        this.btnGuardar.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        if (validarFormulario()) {
            guardarActividad();
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void guardarActividad() {
        if (!validarFechas(this.txtFechaInicio.getText(), this.txtFechaFin.getText())) {
            return;
        }
        
        if (!validarEstatus()) {
            return;
        }
        
        try {
            Actividades act = new Actividades(Integer.parseInt(this.txtNumAct.getText()), this.txtNomAct.getText(), this.txtFechaInicio.getText(), this.txtFechaFin.getText(), this.cboEstatusAct.getSelectedItem().toString(), this.cboIDsCliente.getSelectedItem().toString()
                    , this.txtApellidoCliente.getText(), this.txtNombresCliente.getText(), this.txtTelefonoCliente.getText(), this.cboIDsEmpleado.getSelectedItem().toString(), this.txtApellidoEmpleado.getText(),
                    this.txtNombresEmpleado.getText(), this.txtCurp.getText(), this.txtArea.getText(), this.txtPuesto.getText());
            try (BufferedWriter bw = new BufferedWriter(new FileWriter("actividades.txt", true))) {
                bw.write(act.toString());
                bw.newLine();
            }
            JOptionPane.showMessageDialog(null, "La actividad se guardo correctamnente.", "Exito", 1);
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar: " + e.getMessage(), "ERROR", 0);
        }
    }
    
    private boolean validarFechas(String fechaInicio, String fechaFin) {
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        formatoFecha.setLenient(false);
        
        try {
            formatoFecha.parse(fechaInicio);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "La fecha de Inicio tiene un formato invalido. \nEl formato correcto es dd/MM/yyyy.", "ADVERTENCIA: Formato incorrecto", 2);
            this.txtFechaInicio.requestFocus();
            return false;
        }
        
        try {
            formatoFecha.parse(fechaFin);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "La fecha de Fin tiene un formato invalido. \nEl formato correcto es dd/MM/yyyy.", "ADVERTENCIA: Formato incorrecto", 2);
            this.txtFechaFin.requestFocus();
            return false;
        }
        return true;
    }
    
    
    private boolean validarTextField(JTextField textField, String mensaje) {
        if (textField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, mensaje);
            textField.requestFocus();
            return false;
        }
        return true;
    }
    
    private boolean validarComboBox(JComboBox<String> comboBox, String mensaje) {
        if (comboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, mensaje);
            comboBox.requestFocus();
            return false;
        }
        return true;
    }
    
    private boolean validarFormulario() {
        if (!validarTextField(this.txtNumAct, "El campo Num. de Actividad esta vacio.")) return false;
        if (!validarTextField(this.txtNomAct, "El campo Nombre de Actividad esta vacio.")) return false;
        if (!validarTextField(this.txtFechaInicio, "El campo Fecha de Inicio esta vacio.")) return false;
        if (!validarTextField(this.txtFechaFin, "El campo Fecha Apor. de Fin esta vacio.")) return false;
        if (!validarTextField(this.txtApellidoCliente, "El campo Apellido en el cliente esta vacio.")) return false;
        if (!validarTextField(this.txtNombresCliente, "El campo Nombre en el cliente esta vacio.")) return false;
        if (!validarTextField(this.txtTelefonoCliente, "El campo Telefono en el cliente esta vacio.")) return false;
        if (!validarTextField(this.txtApellidoEmpleado, "El campo Apellido en el Empleado esta vacio.")) return false;
        if (!validarTextField(this.txtNombresEmpleado, "El campo Nombre en el Empleado esta vacio.")) return false;
        if (!validarTextField(this.txtCurp, "El campo Curp en el Empleado esta vacio.")) return false;
        if (!validarTextField(this.txtArea, "El campo Area de Empleo esta vacio.")) return false;
        if (!validarTextField(this.txtPuesto, "El campo Puesto de Empleo esta vacio.")) return false;
        
        if (!validarComboBox(this.cboEstatusAct, "Debe seleccionar un Estatus de la Actividad.")) return false;
        if (!validarComboBox(this.cboIDsCliente, "Debe seleccionar un ID de Cliente.")) return false;
        if (!validarComboBox(this.cboIDsEmpleado, "Debe seleccionar un ID de Empleado.")) return false;
        return true;
    }
    
    private boolean validarEstatus() {
        String estatusCliente = this.txtEstatusCliente.getText();
        String estatusEmpleado = this.txtEstatusEmpleado.getText();
        
        if (estatusCliente.equals("-- Inactivo --")) {
            JOptionPane.showMessageDialog(null, "El estatus del cliente es inactivo no puedes agregarlo a la actividad. \nCambia el estatus del cliente en Editar Cliente", "ERROR: Cliente Inactivo", 0);
            return false;
        }
        
        if (estatusEmpleado.equals("-- Inactivo --") || estatusEmpleado.equals("-- En Capacitacion --")) {
            JOptionPane.showMessageDialog(null, "El estatus del empleado es inactivo o en capacitacion no puedes agregarlo a la actividad. \nCambia el estatus del cliente en Editar Empleado en el Menu Gestor de Empresa", "ERROR: Empleado inactivo o en capacitacion", 0);
            return false;
        }
        
        return true;
    }
    
    private void configurarComponentesCliente() {
        this.txtApellidoCliente.setEnabled(false);
        this.txtNombresCliente.setEnabled(false);
        this.txtTelefonoCliente.setEnabled(false);
        this.txtEstatusCliente.setEnabled(false);
    }
    
    private void configurarComponentesEmpleado() {
        this.txtApellidoEmpleado.setEnabled(false);
        this.txtNombresEmpleado.setEnabled(false);
        this.txtCurp.setEnabled(false);
        this.txtArea.setEnabled(false);
        this.txtPuesto.setEnabled(false);
        this.txtEstatusEmpleado.setEnabled(false);
    }
    
    private void actualizarComponentesClientes() {
        this.txtApellidoCliente.setEnabled(true);
        this.txtNombresCliente.setEnabled(true);
        this.txtTelefonoCliente.setEnabled(true);
        this.txtEstatusCliente.setEnabled(true);
    }
    
    private void actualizarComponentesEmpleado() {
        this.txtApellidoEmpleado.setEnabled(true);
        this.txtNombresEmpleado.setEnabled(true);
        this.txtCurp.setEnabled(true);
        this.txtArea.setEnabled(true);
        this.txtPuesto.setEnabled(true);
        this.txtEstatusEmpleado.setEnabled(true);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboEstatusAct;
    private javax.swing.JComboBox<String> cboIDsCliente;
    private javax.swing.JComboBox<String> cboIDsEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtEstatusCliente;
    private javax.swing.JTextField txtEstatusEmpleado;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtNomAct;
    private javax.swing.JTextField txtNombresCliente;
    private javax.swing.JTextField txtNombresEmpleado;
    private javax.swing.JTextField txtNumAct;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
