/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import ClasesUtilitarias.ArchivoUtilActividades;
import java.awt.Color;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josea
 */
public class BorrarActividad extends javax.swing.JPanel {

    /**
     * Creates new form BorrarActividad
     */
    public BorrarActividad() {
        initComponents();
        cargarNombresAct();
        cargarColumnasTabla();
    }
    
    private void cargarColumnasTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Num. Act", "Nombre Act.", "F. Inicio", "F. Aprox. Fin.",  "Estatus Act"});
        this.tblActividad.setModel(modelo);
    }
    
    private void cargarNombresAct() {
        this.cboNombreAct.removeAllItems();
        this.cboNombreAct.addItem("-- Selecciona el nombre de una Act --");
        
        List<String[]> datos = ArchivoUtilActividades.leerArchivo("actividades.txt");
        for (String[] fila : datos) {
            this.cboNombreAct.addItem(fila[1]);
        }
        
    }
    
    private void cargarDatosActividad() {
        if (this.cboNombreAct.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Selecciona un Nombre de una Actividad", "INFO", 1);
            return;
        }
        
        String nombreActSeleccionada = (String) this.cboNombreAct.getSelectedItem();
        List<String[]> datos = ArchivoUtilActividades.leerArchivo("actividades.txt");
        limpiarTabla();
        
        for (String[] fila : datos) {
            if (fila[1].equals(nombreActSeleccionada)) {
                DefaultTableModel model = (DefaultTableModel) this.tblActividad.getModel();
                model.addRow(new Object[]{fila[0], fila[1], fila[2],fila[3], fila[4]});
                break;
            }
        }
    }
    
    private void limpiarTabla() {
        DefaultTableModel model = (DefaultTableModel) this.tblActividad.getModel();
        model.setRowCount(0);
    }
    
    private void eliminarActividad() {
        if (this.cboNombreAct.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un Nombre de una Actividad.", "ADVERTENCIA: No hya seleccion de Actividad", 2);
            return; 
        }
        
        String nombreActSeleccionado = (String) this.cboNombreAct.getSelectedItem();
        List<String[]> datos = ArchivoUtilActividades.leerArchivo("actividades.txt");
        boolean encontrado = false;
        
        for (int i = 0; i < datos.size(); i++) {
            if (datos.get(i)[1].equals(nombreActSeleccionado)) {
                datos.remove(i);
                encontrado = true;
                break;
            }
        }
        
        if (encontrado) {
            ArchivoUtilActividades.escribirArchivo("actividades.txt", datos);
            JOptionPane.showMessageDialog(null, "Actividad eliminada correctamente.", "Exito", 1);
            limpiarTabla();
            cargarNombresAct();
        } else {
            JOptionPane.showMessageDialog(null, "No se encontro a la actividad con el nombre seleccionado", "ERROR: Actividad no encontrada", 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboNombreAct = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActividad = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jLabel1.setText("Eliminar Actividad de la Actividad");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 20, 440, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/clipboard_7249124.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 80, 60);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Datos de actvidad:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 80, 200, 20);

        cboNombreAct.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        cboNombreAct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNombreAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNombreActActionPerformed(evt);
            }
        });
        jPanel2.add(cboNombreAct);
        cboNombreAct.setBounds(660, 10, 340, 30);

        jScrollPane1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        tblActividad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblActividad);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 1040, 110);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("Selecciona un nombre de la actividad en el Combo Box para eliminarlo:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 660, 20);

        btnEliminar.setBackground(new java.awt.Color(0, 0, 153));
        btnEliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/clipboard_7249124.png"))); // NOI18N
        btnEliminar.setText("Eliminar Reporte");
        btnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        jPanel2.add(btnEliminar);
        btnEliminar.setBounds(260, 280, 530, 120);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void cboNombreActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNombreActActionPerformed
        cargarDatosActividad();
    }//GEN-LAST:event_cboNombreActActionPerformed

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        this.btnEliminar.setBackground(Color.red);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        this.btnEliminar.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        eliminarActividad();
    }//GEN-LAST:event_btnEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cboNombreAct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblActividad;
    // End of variables declaration//GEN-END:variables
}
