/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import ClasesUtilitarias.ArchivoUtilClientes;
import java.util.List;
import Objeto.*;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author josea
 */
public class ClientesReportes extends javax.swing.JPanel {

    /**
     * Creates new form ReportesClientes
     */
    public ClientesReportes() {
        initComponents();
        configurarComponentes();
    }
    
    private void generarReporte() {
        String tipoReporte = (String) this.cboTipoReporte.getSelectedItem();
        List<String[]> datos = ArchivoUtilClientes.leerArchivo("clientes.txt");
        
        switch (tipoReporte) {
            case "-- Reporte General de Clientes --":
                if (ReportesClientes.generarReporteGeneral(datos, "ReporteGeneral.pdf"))
                    mostrarMensajeExito("Reporte General de Clientes generado.");
                break;
            case "-- Reporte por Estatus --":
                String estatus = (String) this.cboEstatus.getSelectedItem();
                if ("-- Selecciona un Estatus --".equals(estatus)) {
                    mostrarMensajeError("Debe seleccionar un estatus.");
                    return;
                }
                
                if (ReportesClientes.generarReportePorEstatus(datos, estatus, "ReportePorEstatus.pdf"))
                    mostrarMensajeExito("Reporte de Clientes por Estatus generado.");
                break;
            case "-- Reporte por Fecha de Registro --":
                String fechaRegistro = this.txtFechaRegistro.getText();
                if (fechaRegistro.isEmpty()) {
                    mostrarMensajeError("Ingresa una fecha de Registro.");
                    return;
                }
                
                if (ReportesClientes.generarReportePorFechaRegistro(datos, fechaRegistro, "ReportePorFechaRegistro.pdf")) {
                    mostrarMensajeExito("Reporte de Clientes por Fecha de Registro generado.");
                }
                break;
            default:
                mostrarMensajeError("Debe seleccionar un Tipo de Reporte.");
        }
    }
    
    private void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Exito", 1);
    }
    
    private void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "ADVERTENCIA", 2);
    }
    
    private void configurarComponentes() {
        this.cboEstatus.setEnabled(false);
        this.txtFechaRegistro.setEnabled(false);
    }
    
    private void actualizarComponentes() {
        String seleccion = (String) this.cboTipoReporte.getSelectedItem();
        
        switch (seleccion) {
            case "-- Reporte General de Clientes --":
                this.cboEstatus.setEnabled(false);
                this.txtFechaRegistro.setEnabled(false);
                this.lblInfo.setForeground(Color.black);
                this.lblInfo.setText("Reporte General no necesitas ingresar datos.");
                break;
            case "-- Reporte por Estatus --":
                this.cboEstatus.setEnabled(true);
                this.txtFechaRegistro.setEnabled(false);
                this.lblInfo.setForeground(Color.black);
                this.lblInfo.setText("Selecciona un Estatus especifico.");
                break;
            case "-- Reporte por Fecha de Registro --":
                this.cboEstatus.setEnabled(false);
                this.txtFechaRegistro.setEnabled(true);
                this.lblInfo.setForeground(Color.black);
                this.lblInfo.setText("Ingresa una fecha de Registro con el formato dd/MM/yyyy.");
                break;
            default:
                this.cboEstatus.setEnabled(false);
                this.txtFechaRegistro.setEnabled(false);
                this.lblInfo.setForeground(Color.red);
                this.lblInfo.setText("Elije un tipo de reporte.");
                break;
        }
    }
    
    private void limpiar() {
        this.cboEstatus.setSelectedItem("-- Selecciona un Estatus --");
        this.txtFechaRegistro.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboTipoReporte = new javax.swing.JComboBox<>();
        lblInfo = new javax.swing.JLabel();
        cboEstatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFechaRegistro = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Generar Reportes de Clientes.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 30, 420, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/reportes clientes.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 70);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 21)); // NOI18N
        jLabel3.setText("Selecciona un tipo de reporte en el Combo Box para poder generarlo:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 30, 720, 30);

        cboTipoReporte.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        cboTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--  Selecciona un Tipo de Reporte --", "-- Reporte General de Clientes --", "-- Reporte por Estatus --", "-- Reporte por Fecha de Registro --" }));
        cboTipoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoReporteActionPerformed(evt);
            }
        });
        jPanel2.add(cboTipoReporte);
        cboTipoReporte.setBounds(710, 20, 370, 40);

        lblInfo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblInfo.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 153)));
        jPanel2.add(lblInfo);
        lblInfo.setBounds(460, 230, 460, 60);

        cboEstatus.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        cboEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona un Estatus --", "-- Activo --", "-- Inactivo --" }));
        jPanel2.add(cboEstatus);
        cboEstatus.setBounds(160, 130, 270, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel5.setText("Ingresa la fecha de Registro:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(430, 140, 250, 30);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel6.setText("Elije un Estatus:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 140, 150, 30);

        txtFechaRegistro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jPanel2.add(txtFechaRegistro);
        txtFechaRegistro.setBounds(670, 140, 350, 40);

        btnGenerar.setBackground(new java.awt.Color(0, 0, 153));
        btnGenerar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Icono Generar Reportes grande.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarMouseExited(evt);
            }
        });
        jPanel2.add(btnGenerar);
        btnGenerar.setBounds(80, 280, 370, 140);

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 153));
        btnLimpiar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/broom_2376996.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
        });
        jPanel2.add(btnLimpiar);
        btnLimpiar.setBounds(490, 310, 390, 100);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1090, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseEntered
        this.btnGenerar.setBackground(Color.green);
    }//GEN-LAST:event_btnGenerarMouseEntered

    private void btnGenerarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseExited
        this.btnGenerar.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnGenerarMouseExited

    private void btnGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseClicked
        generarReporte();
    }//GEN-LAST:event_btnGenerarMouseClicked

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        this.btnLimpiar.setBackground(Color.red);
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        this.btnLimpiar.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        limpiar();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void cboTipoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoReporteActionPerformed
        actualizarComponentes();
    }//GEN-LAST:event_cboTipoReporteActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboEstatus;
    private javax.swing.JComboBox<String> cboTipoReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTextField txtFechaRegistro;
    // End of variables declaration//GEN-END:variables
}
