/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import Modelo.Manual;
import java.awt.Color;

/**
 *
 * @author josea
 */
public class InstruccionesClientes extends javax.swing.JPanel {

    /**
     * Creates new form InstruccionesClientes
     */
    public InstruccionesClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnManualUsuario = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setText("Instrucciones (Gestor de Clientes).");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/abstract-blue-backgroundr.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Nota: en esta seccion tiene todas las opciones juntas (Agregar, Lista, Editar y Borrar)  a diferencia de seccion clientes.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 150, 700, 20);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 254));
        jLabel4.setText("Seccion Reportes:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 290, 240, 30);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel5.setText("4. Borrar Cliente: Aqui tendras que seleccionar un ID en un combo box, seleciona un ID y veras los datos de ese ID para eliminar al cliente al dar click en \"Eliminar\"");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 120, 1070, 20);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel6.setText("tienen su estatus como inactivo o en capacitacion esta ultima en empleado no se podra añadirlo a la actividad hasta que su estatus este en Activo.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 190, 1080, 20);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel7.setText("2. Lista Clientes; Aqui podras ver los datos de los clientes ordenados por columnas asi para saber cuantos se tienen guardados.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 60, 1070, 20);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel8.setText("3. Editar Cliente: Aqui tendras un combo box que almacena todos los ID de los clientes. Selecciona uno y apareceran sus datos en los campos correspondientes para");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 80, 1070, 20);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel9.setText("ser editados en caso de informacion erronea, despues dar click en \"Actualizar\" para que asi los datos se actualizen y sean visibles en la tabla de clientes.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 100, 1070, 20);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 254));
        jLabel10.setText("Seccion Clientes:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 20, 240, 30);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Siempre que cambies de menu abre el menu desplegable y da click en una de las opciones.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 0, 910, 30);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel12.setText("1. Agregar Cliente: Ingresa todos los datos que se te indiquen y despues dar click en \"Guardar\" para guardar al cliente a la lista de Clientes.");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 40, 1070, 20);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel13.setText("los datos y sean visibles en la lista. Si estatus de cliente esta inactivo o empleado inactivo o en capacitacion no se podra actualizar los datos.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 250, 1080, 20);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel15.setText("2. Lista Act: Podras la lista de todas la actividades con sus datos correspondientes, al ellimar una actividad esta desaparece de la lista.");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 210, 1080, 20);

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel16.setText("4. Borrar Act: Seleciona un nombre de actividad, veras sus datos basicos en una tabla y da click en \"Borrar\" para eliminar ests actividad de la lista.");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 270, 1080, 20);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel17.setText("3. Editar Act:  Selecciona un nombre de una actividad para cargar todos sus datos en los espacios correspondientes, editalos y da click en \"Actualizar\" para asi cambiar");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 230, 1080, 20);

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 254));
        jLabel18.setText("Seccion Actividades:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 130, 240, 30);

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel19.setText("1. Agregar Act: Llena los datos de la ctividad despues un ID de un cliente y cargaran sus datos basicos, haz lo mismo en datos de empleado. OJO si un cliente o empleado");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 170, 1080, 20);

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel20.setText("1. Generar Reportes: Podras hacer reportes tanto de clientes como de Actividades la funcionalidad es la misma que en el primer gestor.");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 310, 1080, 20);

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel21.setText("2, Lista de Reportes: Podras ver todos los reportes hechos y guardarlos para abrirlos en \"Mi Gestor\" de ese segundo Gestor.");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 330, 1080, 20);

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel22.setText("3. Eliminar Reportes: Selecciona un reporte en un combo box y dar click en \"Eliminar Reporte\" este solo se eliminara de la lista pero no de \"Mi Gestor\"");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 350, 1080, 20);

        btnManualUsuario.setBackground(new java.awt.Color(0, 0, 153));
        btnManualUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnManualUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnManualUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/guide-book_5639208.png"))); // NOI18N
        btnManualUsuario.setText("Manual de Usuario");
        btnManualUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnManualUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManualUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManualUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManualUsuarioMouseExited(evt);
            }
        });
        jPanel1.add(btnManualUsuario);
        btnManualUsuario.setBounds(300, 380, 420, 80);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManualUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManualUsuarioMouseEntered
        this.btnManualUsuario.setBackground(Color.green);
    }//GEN-LAST:event_btnManualUsuarioMouseEntered

    private void btnManualUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManualUsuarioMouseExited
        this.btnManualUsuario.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnManualUsuarioMouseExited

    private void btnManualUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManualUsuarioMouseClicked
        Modelo.Manual manual = new Manual();
        manual.abrirManual();
    }//GEN-LAST:event_btnManualUsuarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManualUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
