/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import Modelo.Manual;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author josea
 */
public class Isntrucciones extends javax.swing.JPanel {

    /**
     * Creates new form Isntrucciones
     */
    public Isntrucciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnManualUsuario = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setText("Instrucciones para ocupar el programa");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 500, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/abstract-blue-backgroundr.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Instrucciones de ese Menu para mas informacion o abre el manual de usuario en la pagina oficial.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 360, 1040, 30);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("en \"Generar Reporte\" para asi crearlo dar click en \"Limpiar datos\" para borrar el contenido y reiniciar los combo Box");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 220, 1070, 20);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Seccion Reportes:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 160, 206, 30);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("1. Agregar Empleado: Ingresa todos los datos correspondientes y dar clic al boton guardar para asi agregarlo a la lista.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 70, 1070, 20);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setText("2. Lista de Empleados: Su unica funcion es poder ver a todos los empleados que has agregado. Si los haz eleminado no se veran en la lista (tabla).");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 90, 1070, 20);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("3. Editar Empleado: Edita todos sus datos al darle al boton actualizan sus datos se muestran actualizados en la lista de empleados.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 110, 1070, 20);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Seccion Empleados:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 37, 206, 30);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setText("4. Eleminar Empleado: selecciona un ID de un empleado darle click al boton \"Borrar\" y este empleado no se mostrara en la lista de Empleados.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 130, 1070, 20);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("\"Mi Gestor\" en el \"Menu Principal\" al seleccionarlo o borrar para siempre ese reporte.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 260, 1070, 20);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("5. Generar Reportes: Selecciona un tipo de reporte y llena la informacion dependiendo de que tipo de reporte hayas seleccionado despues dar");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 200, 1070, 20);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setText("7. Eleminar Reporte: selecciona un reporte ya existente y dar click en el boton e\"Eleminar\" para asi quitarlo de la lista de reportes.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 280, 1070, 20);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setText("6. Lista de Reportes: Muestra los reportes existentes y al seleccionar uno y darle al boton guardar guardas este reporte y lo puedes abrir desde");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 240, 1070, 20);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Siempre que vayas a cambiar de menu abre el menu desplegable y da click en una de las opciones.");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 10, 900, 30);

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel16.setText("Existe otro menu que es el \"Menu Gestor de Clientes\" encontraras mas informacion llendo al menu y dirigirte alas");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 330, 1040, 30);

        btnManualUsuario.setBackground(new java.awt.Color(0, 0, 102));
        btnManualUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnManualUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnManualUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/guide-book_5639208.png"))); // NOI18N
        btnManualUsuario.setText("Manual de Usuario");
        btnManualUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnManualUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManualUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManualUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManualUsuarioMouseExited(evt);
            }
        });
        jPanel1.add(btnManualUsuario);
        btnManualUsuario.setBounds(330, 400, 450, 80);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManualUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManualUsuarioMouseClicked
        Modelo.Manual manual = new Manual();
        manual.abrirManual();
    }//GEN-LAST:event_btnManualUsuarioMouseClicked

    private void btnManualUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManualUsuarioMouseEntered
        this.btnManualUsuario.setBackground(Color.green);
    }//GEN-LAST:event_btnManualUsuarioMouseEntered

    private void btnManualUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManualUsuarioMouseExited
        this.btnManualUsuario.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnManualUsuarioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManualUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
