/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import ClasesUtilitarias.ArchivoUtilReportesActividades;
import Objeto.ReportesActividades;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.io.IOException;

/**
 *
 * @author josea
 */
public class ListaReportesActividades extends javax.swing.JPanel {
    
    private ArchivoUtilReportesActividades manager = new ArchivoUtilReportesActividades();

    /**
     * Creates new form ListaReportesActividades
     */
    public ListaReportesActividades() {
        initComponents();
        cargarReportes();
    }
    
    private void cargarReportes() {
        String[] reportes = ReportesActividades.listaReportes();
        DefaultListModel<String> modelo = new DefaultListModel<>();
        
        for (String reporte : reportes) {
            modelo.addElement(reporte);
        }
        
        this.lstReportesActividades.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstReportesActividades = new javax.swing.JList<>();
        btnGuardar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seccion Actividades.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(130, 20, 290, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/lista act.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 80, 60);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Click en este boton para guardar el reporte y abrirlo.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(552, 170, 480, 33);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Reportes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 24), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel3.setLayout(null);

        lstReportesActividades.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jScrollPane1.setViewportView(lstReportesActividades);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(11, 31, 490, 380);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 20, 510, 420);

        btnGuardar.setBackground(new java.awt.Color(0, 0, 153));
        btnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/pdf_5200128.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(570, 210, 400, 110);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        this.btnGuardar.setBackground(Color.green);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        this.btnGuardar.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        String reporteSeleccionado = this.lstReportesActividades.getSelectedValue();
        
        if (reporteSeleccionado == null) {
            JOptionPane.showMessageDialog(null, "Selecciona un reporte para guardarlo.", "ADVERTENCIA:  No hay seleccion", 2);
            return; 
        }
        
        try {
            manager.guardarReporte(reporteSeleccionado);
            JOptionPane.showMessageDialog(null, "Reporte guardado correctamente.", "Exito", 1);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al guardar el reporte.", "ERROR", 0);
        }
    }//GEN-LAST:event_btnGuardarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstReportesActividades;
    // End of variables declaration//GEN-END:variables
}
