/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import javax.swing.table.DefaultTableModel;

import ClasesUtilitarias.ArchivoUtilActividades;
import java.util.*;
/**
 *
 * @author josea
 */
public class ListaActividades extends javax.swing.JPanel {

    /**
     * Creates new form ListaActividades
     */
    public ListaActividades() {
        initComponents();
        
        cargarDatos();
    }
    
    private void cargarDatos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{
            "Num. Act", "Nom Act", "F. Inicio", "F. Fin", "Estatus Act" ,"ID Cliente", "Ape. Cliente", "Nom. Cliente", "Tel. Cliente",
            "ID Empleado", "Ape. Emp.", "Nom. Emp.", "CURP", "Area", "Puesto"
        });
        
        List<String[]> datos = ArchivoUtilActividades.leerArchivo("actividades.txt");
        for (String[] fila : datos) 
            modelo.addRow(fila);
        
        this.tblActividades.setModel(modelo);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActividades = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 26)); // NOI18N
        jLabel1.setText("Lista de Actividades");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 20, 350, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/lista act.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 80, 60);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15"
            }
        ));
        jScrollPane1.setViewportView(tblActividades);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 1030, 460);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblActividades;
    // End of variables declaration//GEN-END:variables
}
