/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author josea
 */
public class menu2 extends javax.swing.JPanel {

    /**
     * Creates new form menu2
     */
    public menu2() {
        initComponents();
        
        MiGestorClientes p1 = new MiGestorClientes();
        p1.setSize(1090, 560);
        p1.setLocation(0, 0);
        
        this.content.removeAll();
        this.content.add(p1, BorderLayout.CENTER);
        this.content.revalidate();
        this.content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAcercaDe2 = new javax.swing.JButton();
        btnInstrucciones2 = new javax.swing.JButton();
        btnMiGestor2 = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Menu Principal icon.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(18, 20, 70, 73);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Principal");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 40, 150, 41);

        btnAcercaDe2.setBackground(new java.awt.Color(153, 0, 153));
        btnAcercaDe2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnAcercaDe2.setForeground(new java.awt.Color(255, 255, 255));
        btnAcercaDe2.setText("Acerca De");
        btnAcercaDe2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAcercaDe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcercaDe2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcercaDe2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcercaDe2MouseExited(evt);
            }
        });
        jPanel1.add(btnAcercaDe2);
        btnAcercaDe2.setBounds(320, 20, 140, 73);

        btnInstrucciones2.setBackground(new java.awt.Color(153, 0, 153));
        btnInstrucciones2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnInstrucciones2.setForeground(new java.awt.Color(255, 255, 255));
        btnInstrucciones2.setText("Instrucciones");
        btnInstrucciones2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnInstrucciones2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInstrucciones2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInstrucciones2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInstrucciones2MouseExited(evt);
            }
        });
        jPanel1.add(btnInstrucciones2);
        btnInstrucciones2.setBounds(680, 20, 168, 73);

        btnMiGestor2.setBackground(new java.awt.Color(153, 0, 153));
        btnMiGestor2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnMiGestor2.setForeground(new java.awt.Color(255, 255, 255));
        btnMiGestor2.setText("Mi Gestor Clientes");
        btnMiGestor2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMiGestor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMiGestor2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMiGestor2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMiGestor2MouseExited(evt);
            }
        });
        jPanel1.add(btnMiGestor2);
        btnMiGestor2.setBounds(480, 20, 168, 73);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 110));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1090, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMiGestor2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiGestor2MouseEntered
        this.btnMiGestor2.setBackground(Color.green);
    }//GEN-LAST:event_btnMiGestor2MouseEntered

    private void btnMiGestor2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiGestor2MouseExited
        this.btnMiGestor2.setBackground(new Color(153,0,153));
    }//GEN-LAST:event_btnMiGestor2MouseExited

    private void btnMiGestor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiGestor2MouseClicked
        MiGestorClientes p1 = new MiGestorClientes();
        p1.setSize(1090, 560);
        p1.setLocation(0, 0);
        
        this.content.removeAll();
        this.content.add(p1, BorderLayout.CENTER);
        this.content.revalidate();
        this.content.repaint();
    }//GEN-LAST:event_btnMiGestor2MouseClicked

    private void btnAcercaDe2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaDe2MouseEntered
        this.btnAcercaDe2.setBackground(Color.green);
    }//GEN-LAST:event_btnAcercaDe2MouseEntered

    private void btnAcercaDe2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaDe2MouseExited
        this.btnAcercaDe2.setBackground(new Color(153,0,153));
    }//GEN-LAST:event_btnAcercaDe2MouseExited

    private void btnAcercaDe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaDe2MouseClicked
        AcercaDeClientes p2 = new AcercaDeClientes();
        p2.setSize(1090, 560);
        p2.setLocation(0, 0);
        
        this.content.removeAll();
        this.content.add(p2, BorderLayout.CENTER);
        this.content.revalidate();
        this.content.repaint();
    }//GEN-LAST:event_btnAcercaDe2MouseClicked

    private void btnInstrucciones2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstrucciones2MouseEntered
        this.btnInstrucciones2.setBackground(Color.green);
    }//GEN-LAST:event_btnInstrucciones2MouseEntered

    private void btnInstrucciones2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstrucciones2MouseExited
        this.btnInstrucciones2.setBackground(new Color(153,0,153));
    }//GEN-LAST:event_btnInstrucciones2MouseExited

    private void btnInstrucciones2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstrucciones2MouseClicked
        InstruccionesClientes p3 = new InstruccionesClientes();
        p3.setSize(1090, 560);
        p3.setLocation(0, 0);
        
        this.content.removeAll();
        this.content.add(p3, BorderLayout.CENTER);
        this.content.revalidate();
        this.content.repaint();
    }//GEN-LAST:event_btnInstrucciones2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercaDe2;
    private javax.swing.JButton btnInstrucciones2;
    private javax.swing.JButton btnMiGestor2;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
