/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author josea
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    public Menu() {
        initComponents();
        
        MiGestor panel2 = new MiGestor();
        panel2.setSize(1090, 580);
        panel2.setLocation(0, 0);
        
        this.content.removeAll();
        this.content.add(panel2, BorderLayout.CENTER);
        this.content.revalidate();
        this.content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMiGestor = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Menu Principal icon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Principal");

        btnMiGestor.setBackground(new java.awt.Color(102, 0, 204));
        btnMiGestor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnMiGestor.setForeground(new java.awt.Color(255, 255, 255));
        btnMiGestor.setText("Mi Gestor");
        btnMiGestor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMiGestorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMiGestorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMiGestorMouseExited(evt);
            }
        });

        btnAcercaDe.setBackground(new java.awt.Color(102, 0, 204));
        btnAcercaDe.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnAcercaDe.setForeground(new java.awt.Color(255, 255, 255));
        btnAcercaDe.setText("Acerca De");
        btnAcercaDe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcercaDeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcercaDeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcercaDeMouseExited(evt);
            }
        });

        btnInstrucciones.setBackground(new java.awt.Color(102, 0, 204));
        btnInstrucciones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInstruccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInstruccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInstruccionesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMiGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMiGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1090, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcercaDeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaDeMouseEntered
        this.btnAcercaDe.setBackground(Color.green);
    }//GEN-LAST:event_btnAcercaDeMouseEntered

    private void btnAcercaDeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaDeMouseExited
        this.btnAcercaDe.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_btnAcercaDeMouseExited

    private void btnAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaDeMouseClicked
        AcercaDe panel3 = new AcercaDe();
        panel3.setSize(1090, 580);
        panel3.setLocation(0, 0);
        
        this.content.removeAll();
        this.content.add(panel3, BorderLayout.CENTER);
        this.content.revalidate();
        this.content.repaint();
    }//GEN-LAST:event_btnAcercaDeMouseClicked

    private void btnMiGestorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiGestorMouseEntered
        this.btnMiGestor.setBackground(Color.green);
    }//GEN-LAST:event_btnMiGestorMouseEntered

    private void btnMiGestorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiGestorMouseExited
        this.btnMiGestor.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_btnMiGestorMouseExited

    private void btnMiGestorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiGestorMouseClicked
        MiGestor panel2 = new MiGestor();
        panel2.setSize(1090, 580);
        panel2.setLocation(0, 0);
        
        this.content.removeAll();
        this.content.add(panel2, BorderLayout.CENTER);
        this.content.revalidate();
        this.content.repaint();
    }//GEN-LAST:event_btnMiGestorMouseClicked

    private void btnInstruccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstruccionesMouseEntered
        this.btnInstrucciones.setBackground(Color.green);
    }//GEN-LAST:event_btnInstruccionesMouseEntered

    private void btnInstruccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstruccionesMouseExited
        this.btnInstrucciones.setBackground(new Color(102, 0, 204));
    }//GEN-LAST:event_btnInstruccionesMouseExited

    private void btnInstruccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstruccionesMouseClicked
        Isntrucciones panel4 = new Isntrucciones();
        panel4.setSize(1090, 580);
        panel4.setLocation(0, 0);
        
        this.content.removeAll();
        this.content.add(panel4, BorderLayout.CENTER);
        this.content.revalidate();
        this.content.repaint();
    }//GEN-LAST:event_btnInstruccionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnMiGestor;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
