/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import ClasesUtilitarias.ArchivoUtilReportes;
import java.awt.Color;
import javax.swing.*;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author josea
 */
public class MiGestor extends javax.swing.JPanel {
    
    private ArchivoUtilReportes archivoUtilReportes = new ArchivoUtilReportes();
    private DefaultListModel<String> modeloLista;

    /**
     * Creates new form MiGestor
     */
    public MiGestor() {
        modeloLista = new DefaultListModel<>();
        initComponents();
        this.lstReportesGuardados.setModel(modeloLista);
        cargarReportesGuardados();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstReportesGuardados = new javax.swing.JList<>();
        btnBorrar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setText("Mi Gestor de Empresa \"Azteca Tec\"");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 440, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/abstract-blue-backgroundr.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel2.setText("Reportes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(830, 300, 250, 20);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(820, 30, 10, 440);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(460, 20, 10, 440);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("Mis Documetos (Reportes Guardados)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 10, 350, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Preciat\"");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 330, 340, 20);

        lstReportesGuardados.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lstReportesGuardados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 410, 320);

        btnBorrar.setBackground(new java.awt.Color(0, 0, 102));
        btnBorrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/eliminar pdf.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBorrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBorrarMouseExited(evt);
            }
        });
        jPanel1.add(btnBorrar);
        btnBorrar.setBounds(230, 400, 200, 80);

        btnAbrir.setBackground(new java.awt.Color(0, 0, 102));
        btnAbrir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnAbrir.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/abrir PDF (2.png"))); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbrirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbrirMouseExited(evt);
            }
        });
        jPanel1.add(btnAbrir);
        btnAbrir.setBounds(10, 400, 200, 80);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setText("Principales Actividades:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 20, 280, 40);

        jLabel7.setBackground(new java.awt.Color(0, 0, 102));
        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/curriculum_2726610.png"))); // NOI18N
        jLabel7.setText("Lista Empleados");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 102)));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(830, 140, 250, 40);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("los empleados en la empresa tecnologica");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 80, 340, 20);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setText("Azteca Tec para asi evitar informacion erronea");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(470, 100, 340, 20);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setText("o hasta inclusive perdida de informacion muy");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(470, 120, 340, 20);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("valiosa del empleado.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(470, 140, 340, 20);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("Asi mismo se hacen reportes para asi mejorar");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(470, 160, 340, 20);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setText("el control y el orden de los datos de los emple-");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(470, 180, 340, 20);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setText("ados en la empresa y saber datos en especifi-");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(470, 200, 340, 20);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel15.setText("co de los empleados");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(470, 220, 340, 20);

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel16.setText("La instalacion y creacion de este programa ");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(470, 250, 340, 20);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel17.setText("sujeto a un proyecto antiguo, una version ");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(470, 270, 340, 20);

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel18.setText("beta de este, y al creador Luis Davila Jose");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(470, 290, 340, 20);

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel19.setText("Angel por parte de Cetis 8 \"Rafael Donde");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(470, 310, 340, 20);

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel20.setText("Opciones del programa");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(830, 10, 250, 40);

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel21.setText("Gestionar y mantener un control estable sobre");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(470, 60, 340, 20);

        jLabel22.setBackground(new java.awt.Color(0, 0, 102));
        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/EleminarReporte(Pequeño).png"))); // NOI18N
        jLabel22.setText("Eleminar Reporte");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 102)));
        jPanel1.add(jLabel22);
        jLabel22.setBounds(830, 430, 250, 40);

        jLabel23.setBackground(new java.awt.Color(0, 0, 102));
        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/icono agregarr empleados.png"))); // NOI18N
        jLabel23.setText("Agregar Empleado");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 102)));
        jPanel1.add(jLabel23);
        jLabel23.setBounds(830, 90, 250, 40);

        jLabel24.setBackground(new java.awt.Color(0, 0, 102));
        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/user_16470757.png"))); // NOI18N
        jLabel24.setText("Editar Empleado");
        jLabel24.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 102)));
        jPanel1.add(jLabel24);
        jLabel24.setBounds(830, 190, 250, 40);

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel25.setText("Empleados");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(830, 60, 250, 20);

        jLabel26.setBackground(new java.awt.Color(0, 0, 102));
        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/unemployed_7557115.png"))); // NOI18N
        jLabel26.setText("Borrar Empleado");
        jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 102)));
        jPanel1.add(jLabel26);
        jLabel26.setBounds(830, 240, 250, 40);

        jLabel27.setBackground(new java.awt.Color(0, 0, 102));
        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Icono Generar Reportes pequeño.png"))); // NOI18N
        jLabel27.setText("Generar Reportes");
        jLabel27.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 102)));
        jPanel1.add(jLabel27);
        jLabel27.setBounds(830, 330, 250, 40);

        jLabel28.setBackground(new java.awt.Color(0, 0, 102));
        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/ListaReportes.png"))); // NOI18N
        jLabel28.setText("Lista Reportes");
        jLabel28.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 102)));
        jPanel1.add(jLabel28);
        jLabel28.setBounds(830, 380, 250, 40);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void cargarReportesGuardados() {
        try {
            List<String> reportes = archivoUtilReportes.cargarReportesGuardados();
            for (String reporte : reportes) 
                modeloLista.addElement(reporte);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", 0);
        }
    }
    
    private void btnBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseEntered
        this.btnBorrar.setBackground(Color.red);
    }//GEN-LAST:event_btnBorrarMouseEntered

    private void btnBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseExited
        this.btnBorrar.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnBorrarMouseExited

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        String reporteSeleccionado = this.lstReportesGuardados.getSelectedValue();
        
        if (reporteSeleccionado == null) {
            JOptionPane.showMessageDialog(null, "Seleccione un reporte para borrar.", "ERROR: No hay seleccion de reporte", 0);
            return;
        }
        
        try {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estas Seguro(@) de querer borrar el reporte?", "Corfirmar respuesta", JOptionPane.YES_NO_OPTION, 3);
            if (confirmacion == JOptionPane.YES_OPTION) {
                if (archivoUtilReportes.borrarReporte(reporteSeleccionado)) {
                    JOptionPane.showMessageDialog(null, "Reporte: " + reporteSeleccionado + " eleminado exitosamente"
                            , "Exito", 1);
                }
            } else {
                
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnBorrarMouseClicked

    private void btnAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseClicked
        String reporteSeleccionado = this.lstReportesGuardados.getSelectedValue();
        
        if (reporteSeleccionado == null) {
            JOptionPane.showMessageDialog(null, "Seleccione un reporte para abrir.", "ERROR: No hay seleccion de reporte", 0);
            return;
        }
        
        try {
            archivoUtilReportes.abrirReporte(reporteSeleccionado);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", 0);
        }
    }//GEN-LAST:event_btnAbrirMouseClicked

    private void btnAbrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseEntered
        this.btnAbrir.setBackground(Color.green);
    }//GEN-LAST:event_btnAbrirMouseEntered

    private void btnAbrirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseExited
        this.btnAbrir.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnAbrirMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList<String> lstReportesGuardados;
    // End of variables declaration//GEN-END:variables
}
