/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package subpanelesmenu;

import ClasesUtilitarias.*;
import java.awt.Color;
import java.util.*;
import javax.swing.*;
import java.io.IOException;

/**
 *
 * @author josea
 */
public class MiGestorClientes extends javax.swing.JPanel {
    
    private ArchivoUtilReportesClientes reportesClientesUtil = new ArchivoUtilReportesClientes();
    private ArchivoUtilReportesActividades reportesActividadesUtil = new  ArchivoUtilReportesActividades();
    private DefaultListModel<String> modeloLista1;
    private DefaultListModel<String> modeloLista2;

    /**
     * Creates new form MiGestorClientes
     */
    public MiGestorClientes() {
        modeloLista1 = new DefaultListModel<>();
        modeloLista2 = new DefaultListModel<>();
        initComponents();
        this.lstReportesGuardadosClientes.setModel(modeloLista1);
        this.lstReportesGuardadosAct.setModel(modeloLista2);
        cargarReportesGuardadosClientes();
        cargarReportesGuardadosActividades();
    }
    
    private void cargarReportesGuardadosClientes() {
        try {
            List<String> reportes = reportesClientesUtil.cargarReportesGuardados();
            for (String reporte : reportes) {
                modeloLista1.addElement(reporte);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", 0);
        }
    }
    
    private void cargarReportesGuardadosActividades() {
        try {
            List<String> reportes = reportesActividadesUtil.cargarReportesGuardados();
            for (String reporte : reportes) {
                modeloLista2.addElement(reporte);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstReportesGuardadosClientes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstReportesGuardadosAct = new javax.swing.JList<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("Mi Gestor de Clientes \"Azteca Tec\".");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/abstract-blue-backgroundr.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Opciones de uso");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(870, 20, 200, 30);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(860, 10, 10, 440);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("Archivos Guardados (Reportes)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 10, 300, 30);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setText("Principales Actividades.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 20, 230, 30);

        btnBorrar.setBackground(new java.awt.Color(0, 0, 153));
        btnBorrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/eliminar pdf.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBorrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBorrarMouseExited(evt);
            }
        });
        jPanel1.add(btnBorrar);
        btnBorrar.setBounds(280, 370, 210, 80);

        btnAbrir.setBackground(new java.awt.Color(0, 0, 153));
        btnAbrir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnAbrir.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/abrir PDF (2.png"))); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbrirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbrirMouseExited(evt);
            }
        });
        jPanel1.add(btnAbrir);
        btnAbrir.setBounds(40, 370, 220, 80);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel2.setLayout(null);

        lstReportesGuardadosClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(lstReportesGuardadosClientes);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 250, 280);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 200, 280);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 280, 310);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actividades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel3.setLayout(null);

        lstReportesGuardadosAct.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(lstReportesGuardadosAct);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 240, 280);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(300, 50, 260, 310);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(570, 20, 10, 440);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel6.setText("ventana instrucciones");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 230, 270, 20);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel7.setText("A diferencia del primer gestor en este solo");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(580, 60, 270, 20);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel8.setText("se enfoca en gestionar clientes y activida-");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(580, 80, 270, 20);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel9.setText("des  en la empresa dando otros datos y ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(580, 100, 270, 20);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel10.setText("otras funcionalidades y de ampliar mas la");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(580, 120, 270, 20);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel11.setText("informacion y el control de la empresa");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(580, 140, 270, 20);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel12.setText("Si necesitas obtener mas informacion ve");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(580, 170, 270, 20);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel13.setText("alas instrucciones y lee el contenido o ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(580, 190, 270, 20);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel14.setText("abre el manual de usuario en la misma ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(580, 210, 270, 20);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/EleminarReporte(Pequeño).png"))); // NOI18N
        jLabel15.setText("EliminarReporte");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(870, 410, 208, 40);

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Cliente Pequeño.png"))); // NOI18N
        jLabel16.setText("Agregar  Cliente");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(870, 60, 208, 40);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/ListaClientes para boton.png"))); // NOI18N
        jLabel17.setText("Lista Clientes");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(870, 110, 208, 40);

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/interview_901407.png"))); // NOI18N
        jLabel18.setText("Editar Cliente");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        jPanel1.add(jLabel18);
        jLabel18.setBounds(870, 160, 208, 40);

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/user_6639357.png"))); // NOI18N
        jLabel19.setText("Borrar Cliente");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        jPanel1.add(jLabel19);
        jLabel19.setBounds(870, 210, 208, 40);

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/user_6639357.png"))); // NOI18N
        jLabel20.setText("Gestor Actividades");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        jPanel1.add(jLabel20);
        jLabel20.setBounds(870, 260, 208, 40);

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Icono Generar Reportes pequeño.png"))); // NOI18N
        jLabel21.setText("Generar Reportes");
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        jPanel1.add(jLabel21);
        jLabel21.setBounds(870, 310, 208, 40);

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/ListaReportes.png"))); // NOI18N
        jLabel22.setText("Lista Reportes");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        jPanel1.add(jLabel22);
        jLabel22.setBounds(870, 360, 208, 40);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1090, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseEntered
        this.btnAbrir.setBackground(Color.green);
    }//GEN-LAST:event_btnAbrirMouseEntered

    private void btnAbrirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseExited
        this.btnAbrir.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnAbrirMouseExited

    private void btnAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseClicked
        String reporteSeleccionadoC = this.lstReportesGuardadosClientes.getSelectedValue();
        String reporteSeleccionadoAct = this.lstReportesGuardadosAct.getSelectedValue();
        
        if (reporteSeleccionadoC != null) {
            try {
                reportesClientesUtil.abrirReporte(reporteSeleccionadoC);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", 0);
            }
        } else if (reporteSeleccionadoAct != null) {
            try {
                reportesActividadesUtil.abrirReporte(reporteSeleccionadoAct);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un reporte para abrirlo", "ADVERTENCIA: No hay seleccion de reporte", 2);
        }
        
    }//GEN-LAST:event_btnAbrirMouseClicked

    private void btnBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseEntered
        this.btnBorrar.setBackground(Color.red);
    }//GEN-LAST:event_btnBorrarMouseEntered

    private void btnBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseExited
        this.btnBorrar.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnBorrarMouseExited

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        String reporteSeleccionadoC = this.lstReportesGuardadosClientes.getSelectedValue();
        String reporteSeleccionadoAct = this.lstReportesGuardadosAct.getSelectedValue();
        
        if (reporteSeleccionadoC != null) {
            try {
                int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estas seguro(@) de querer borrar el reportee?", "Confirmar respuesta",
                        JOptionPane.YES_NO_OPTION, 3);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    if (reportesClientesUtil.borrarReporte(reporteSeleccionadoC)) {
                        JOptionPane.showMessageDialog(null, "Reporte " + reporteSeleccionadoC + " borrado exitosamente",
                                "Exito de eliminacion", 1);
                    }
                } else {
                    
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if (reporteSeleccionadoAct != null) {
            try {
                int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estas seguro(@) de querer borrar el reportee?", "Confirmar respuesta",
                        JOptionPane.YES_NO_OPTION, 3);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    if (reportesActividadesUtil.borrarReporte(reporteSeleccionadoAct)) {
                        JOptionPane.showMessageDialog(null, "Reporte " + reporteSeleccionadoAct + " borrado exitosamente",
                                "Exito de eliminacion", 1);
                    }
                } else {
                    
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un reporte para borrarlo.", "ADVERTENCIA: No hay seleccion de reporte", 2);
        }
    }//GEN-LAST:event_btnBorrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JList<String> lstReportesGuardadosAct;
    private javax.swing.JList<String> lstReportesGuardadosClientes;
    // End of variables declaration//GEN-END:variables
}
