/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import subpanelesmenu.menu2;
import paneles.*;

/**
 *
 * @author josea
 */
public class MenuSecundario extends javax.swing.JFrame {
    
    private boolean isMenuOpen = false;
    private Timer timer;

    /**
     * Creates new form MenuSecundario
     */
    public MenuSecundario() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Recursos/tribal - Editado.png")).getImage());
        
        iniciarReloj();
        
        menu2 sec = new menu2();
        sec.setSize(1090, 670);
        sec.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(sec);
        this.contenido.revalidate();
        this.contenido.repaint();
    }
    
    private void iniciarReloj() {
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); // Configuramos el formato de fecha y hora.
        // Creamos el Timer para que se ejecute a cada segundo.
        timer = new Timer(1000, e-> { 
           //Obtenemos la fecha y hora actual.
           Date ahora = new Date();
           this.lblFecha.setText(formatoFecha.format(ahora));
        }); 
        timer.start();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        btnMenuGestorPrincipal = new javax.swing.JButton();
        btnListaClientes = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnBorrarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        btnGestorAct = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        btnListaReportes = new javax.swing.JButton();
        btnEliminarReporte = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDesplegar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Gestor de Clientes y Actividades en la Empresa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        menu.setBackground(new java.awt.Color(0, 0, 153));
        menu.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menus");
        menu.add(jLabel1);
        jLabel1.setBounds(100, 0, 160, 40);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reportes:");
        menu.add(jLabel2);
        jLabel2.setBounds(10, 340, 110, 30);

        btnSalir.setBackground(new java.awt.Color(0, 0, 153));
        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/exit_icon.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        menu.add(btnSalir);
        btnSalir.setBounds(50, 730, 280, 50);

        btnMenuPrincipal.setBackground(new java.awt.Color(0, 0, 153));
        btnMenuPrincipal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/clean-house_3672451.png"))); // NOI18N
        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuPrincipalMouseExited(evt);
            }
        });
        menu.add(btnMenuPrincipal);
        btnMenuPrincipal.setBounds(20, 630, 340, 40);

        btnAgregarCliente.setBackground(new java.awt.Color(0, 0, 153));
        btnAgregarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnAgregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Cliente Pequeño.png"))); // NOI18N
        btnAgregarCliente.setText("Agregar Cliente");
        btnAgregarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMouseExited(evt);
            }
        });
        menu.add(btnAgregarCliente);
        btnAgregarCliente.setBounds(20, 50, 340, 40);

        btnMenuGestorPrincipal.setBackground(new java.awt.Color(0, 0, 153));
        btnMenuGestorPrincipal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnMenuGestorPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuGestorPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/manager_9402499.png"))); // NOI18N
        btnMenuGestorPrincipal.setText("Menu Gestor de Empresa");
        btnMenuGestorPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenuGestorPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuGestorPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuGestorPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuGestorPrincipalMouseExited(evt);
            }
        });
        menu.add(btnMenuGestorPrincipal);
        btnMenuGestorPrincipal.setBounds(20, 680, 340, 40);

        btnListaClientes.setBackground(new java.awt.Color(0, 0, 153));
        btnListaClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnListaClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnListaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/ListaClientes para boton.png"))); // NOI18N
        btnListaClientes.setText("Lista Clientes");
        btnListaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaClientesMouseExited(evt);
            }
        });
        menu.add(btnListaClientes);
        btnListaClientes.setBounds(20, 100, 340, 40);

        btnEditarCliente.setBackground(new java.awt.Color(0, 0, 153));
        btnEditarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/interview_901407.png"))); // NOI18N
        btnEditarCliente.setText("Editar Cliente");
        btnEditarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEditarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarClienteMouseExited(evt);
            }
        });
        menu.add(btnEditarCliente);
        btnEditarCliente.setBounds(20, 150, 340, 40);

        btnBorrarCliente.setBackground(new java.awt.Color(0, 0, 153));
        btnBorrarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnBorrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/user_6639357.png"))); // NOI18N
        btnBorrarCliente.setText("Borrar Cliente");
        btnBorrarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnBorrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBorrarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBorrarClienteMouseExited(evt);
            }
        });
        menu.add(btnBorrarCliente);
        btnBorrarCliente.setBounds(20, 200, 340, 40);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        menu.add(jSeparator1);
        jSeparator1.setBounds(10, 330, 360, 10);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Clientes");
        menu.add(jLabel9);
        jLabel9.setBounds(20, 30, 110, 20);

        btnGestorAct.setBackground(new java.awt.Color(0, 0, 153));
        btnGestorAct.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnGestorAct.setForeground(new java.awt.Color(255, 255, 255));
        btnGestorAct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/multitasking_5216804.png"))); // NOI18N
        btnGestorAct.setText("Gestor Actividades");
        btnGestorAct.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnGestorAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestorActMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestorActMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestorActMouseExited(evt);
            }
        });
        menu.add(btnGestorAct);
        btnGestorAct.setBounds(20, 280, 340, 40);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        menu.add(jSeparator2);
        jSeparator2.setBounds(10, 250, 360, 10);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Actividades");
        menu.add(jLabel10);
        jLabel10.setBounds(10, 250, 110, 30);

        btnGenerarReporte.setBackground(new java.awt.Color(0, 0, 153));
        btnGenerarReporte.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Icono Generar Reportes pequeño.png"))); // NOI18N
        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnGenerarReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarReporteMouseExited(evt);
            }
        });
        menu.add(btnGenerarReporte);
        btnGenerarReporte.setBounds(20, 370, 340, 40);

        btnListaReportes.setBackground(new java.awt.Color(0, 0, 153));
        btnListaReportes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnListaReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnListaReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/ListaReportes.png"))); // NOI18N
        btnListaReportes.setText("ListaReportes");
        btnListaReportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnListaReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaReportesMouseExited(evt);
            }
        });
        menu.add(btnListaReportes);
        btnListaReportes.setBounds(20, 420, 340, 40);

        btnEliminarReporte.setBackground(new java.awt.Color(0, 0, 153));
        btnEliminarReporte.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnEliminarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/EleminarReporte(Pequeño).png"))); // NOI18N
        btnEliminarReporte.setText("Eliminar Reporte");
        btnEliminarReporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEliminarReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarReporteMouseExited(evt);
            }
        });
        menu.add(btnEliminarReporte);
        btnEliminarReporte.setBounds(20, 470, 340, 40);

        jPanel3.add(menu);
        menu.setBounds(0, 0, 0, 790);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/azteca tec logo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 10, 220, 220);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Para mas informacion dirigite a;");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 530, 360, 20);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Menu Secundario:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 230, 220, 50);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gestor de Clientes Y");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 270, 240, 40);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Actividades en la");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 300, 210, 40);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Empresa.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 330, 150, 40);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bienvenido al Gestor de Clientes y Acti-");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 380, 360, 20);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("vidades de Azteca Tec donde podras");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 400, 360, 20);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gestionar y mantener un control en los");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 420, 360, 20);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("datos de clientes y actividades, asi");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 440, 360, 20);

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("tambien hacer diferentes tipos de re-");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 460, 360, 20);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("portes ya sea de clientes o de activida-");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 480, 360, 20);

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("correspondiente a esas opciones");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 640, 360, 20);

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("des en la Empresa.");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 500, 360, 20);

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("1. Acerca De");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 560, 360, 20);

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("2. Instrucciones");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 580, 360, 20);

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("En el menu principal presionando el bo-");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 620, 360, 20);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(0, 0, 378, 790);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(null);

        btnDesplegar.setBackground(new java.awt.Color(51, 255, 204));
        btnDesplegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/menu_2550298.png"))); // NOI18N
        btnDesplegar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesplegarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDesplegarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDesplegarMouseExited(evt);
            }
        });
        jPanel2.add(btnDesplegar);
        btnDesplegar.setBounds(17, 15, 78, 71);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Menu Desplegable / Dar click en el para abri el menu desplegable");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(129, 26, 568, 44);

        lblFecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Hora y Fecha Actual");
        jPanel2.add(lblFecha);
        lblFecha.setBounds(740, 30, 370, 30);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(740, 60, 360, 10);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(380, 0, 1110, 100);

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanel3.add(contenido);
        contenido.setBounds(390, 110, 1090, 670);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesplegarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesplegarMouseEntered
        this.btnDesplegar.setBackground(Color.green);
    }//GEN-LAST:event_btnDesplegarMouseEntered

    private void btnDesplegarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesplegarMouseExited
        this.btnDesplegar.setBackground(new Color(51,255,204));
    }//GEN-LAST:event_btnDesplegarMouseExited

    private void btnDesplegarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesplegarMouseClicked
        if (isMenuOpen) {
            closeMenu();
        } else {
            openMenu();
        }
    }//GEN-LAST:event_btnDesplegarMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        this.btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        this.btnSalir.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        int res = JOptionPane.showConfirmDialog(null, "¿Estas Seguro(@) de querer salir?", "Confirmar Salida", JOptionPane.YES_NO_OPTION, 3);
        
        if (res == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "De acuerdo le deseamos un buen dia y regrese pronto.", "Despedida", 1);
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnMenuGestorPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuGestorPrincipalMouseEntered
        this.btnMenuGestorPrincipal.setBackground(Color.green);
    }//GEN-LAST:event_btnMenuGestorPrincipalMouseEntered

    private void btnMenuGestorPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuGestorPrincipalMouseExited
        this.btnMenuGestorPrincipal.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnMenuGestorPrincipalMouseExited

    private void btnMenuGestorPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuGestorPrincipalMouseClicked
        MenuPrincipal ventana1 = new MenuPrincipal();
        ventana1.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnMenuGestorPrincipalMouseClicked

    private void btnAgregarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMouseEntered
        this.btnAgregarCliente.setBackground(Color.green);
    }//GEN-LAST:event_btnAgregarClienteMouseEntered

    private void btnAgregarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMouseExited
        this.btnAgregarCliente.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnAgregarClienteMouseExited

    private void btnAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMouseClicked
        AgregarCliente panel1 = new AgregarCliente();
        panel1.setSize(1090, 670);
        panel1.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel1);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnAgregarClienteMouseClicked

    private void btnListaClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaClientesMouseEntered
        this.btnListaClientes.setBackground(Color.green);
    }//GEN-LAST:event_btnListaClientesMouseEntered

    private void btnListaClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaClientesMouseExited
        this.btnListaClientes.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnListaClientesMouseExited

    private void btnListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaClientesMouseClicked
        ListaClientes panel2 = new ListaClientes();
        panel2.setSize(1090, 670);
        panel2.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel2);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnListaClientesMouseClicked

    private void btnEditarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarClienteMouseEntered
        this.btnEditarCliente.setBackground(Color.green);
    }//GEN-LAST:event_btnEditarClienteMouseEntered

    private void btnEditarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarClienteMouseExited
        this.btnEditarCliente.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnEditarClienteMouseExited

    private void btnEditarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarClienteMouseClicked
        EditarCliente panel3 = new EditarCliente();
        panel3.setSize(1090, 670);
        panel3.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel3);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnEditarClienteMouseClicked

    private void btnBorrarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarClienteMouseEntered
        this.btnBorrarCliente.setBackground(Color.green);
    }//GEN-LAST:event_btnBorrarClienteMouseEntered

    private void btnBorrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarClienteMouseExited
        this.btnBorrarCliente.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnBorrarClienteMouseExited

    private void btnBorrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarClienteMouseClicked
        BorrarCliente panel4 = new BorrarCliente();
        panel4.setSize(1090, 670);
        panel4.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel4);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnBorrarClienteMouseClicked

    private void btnGestorActMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestorActMouseEntered
        this.btnGestorAct.setBackground(Color.green);
    }//GEN-LAST:event_btnGestorActMouseEntered

    private void btnGestorActMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestorActMouseExited
        this.btnGestorAct.setBackground(new  Color(0, 0, 153));
    }//GEN-LAST:event_btnGestorActMouseExited

    private void btnGestorActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestorActMouseClicked
        Actividades panel5 = new Actividades();
        panel5.setSize(1090, 670);
        panel5.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel5);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnGestorActMouseClicked

    private void btnGenerarReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteMouseEntered
        this.btnGenerarReporte.setBackground(Color.green);
    }//GEN-LAST:event_btnGenerarReporteMouseEntered

    private void btnGenerarReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteMouseExited
        this.btnGenerarReporte.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnGenerarReporteMouseExited

    private void btnGenerarReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteMouseClicked
        GenerarReporte2 panel6 = new GenerarReporte2();
        panel6.setSize(1090, 670);
        panel6.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel6);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnGenerarReporteMouseClicked

    private void btnListaReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaReportesMouseEntered
        this.btnListaReportes.setBackground(Color.green);
    }//GEN-LAST:event_btnListaReportesMouseEntered

    private void btnListaReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaReportesMouseExited
        this.btnListaReportes.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnListaReportesMouseExited

    private void btnListaReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaReportesMouseClicked
        ListaReportes2 panel7 = new ListaReportes2();
        panel7.setSize(1090, 670);
        panel7.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel7);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnListaReportesMouseClicked

    private void btnEliminarReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarReporteMouseEntered
        this.btnEliminarReporte.setBackground(Color.green);
    }//GEN-LAST:event_btnEliminarReporteMouseEntered

    private void btnEliminarReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarReporteMouseExited
        this.btnEliminarReporte.setBackground(new  Color(0, 0, 153));
    }//GEN-LAST:event_btnEliminarReporteMouseExited

    private void btnEliminarReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarReporteMouseClicked
        BorrarReporte panel8 = new BorrarReporte();
        panel8.setSize(1090, 670);
        panel8.setLocation(0, 0);
        
         this.contenido.removeAll();
        this.contenido.add(panel8);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnEliminarReporteMouseClicked

    private void btnMenuPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuPrincipalMouseEntered
        this.btnMenuPrincipal.setBackground(Color.green);
    }//GEN-LAST:event_btnMenuPrincipalMouseEntered

    private void btnMenuPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuPrincipalMouseExited
        this.btnMenuPrincipal.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnMenuPrincipalMouseExited

    private void btnMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuPrincipalMouseClicked
        menu2 p = new menu2();
        p.setSize(1090, 670);
        p.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(p);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnMenuPrincipalMouseClicked

    private void openMenu() {
        timer = new Timer(10, new ActionListener() {
            int width = menu.getWidth();
            @Override
            public void actionPerformed(ActionEvent e) {
                if (width < 378) {
                    width += 10;
                    menu.setBounds(0, 0, width, menu.getHeight());
                } else {
                    timer.stop();
                    isMenuOpen = true;
                }
            }
        });
        timer.start();
    }
    
    private void closeMenu() {
        timer = new Timer(10, new ActionListener() {
            int width = menu.getWidth();
            @Override
            public void actionPerformed(ActionEvent e) {
                if (width > 0) {
                    width -= 10;
                    menu.setBounds(0, 0, width, menu.getHeight());
                } else {
                    timer.stop();
                    isMenuOpen = false;
                }
            }
        });
        timer.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSecundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSecundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSecundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSecundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSecundario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnBorrarCliente;
    private javax.swing.JButton btnDesplegar;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEliminarReporte;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnGestorAct;
    private javax.swing.JButton btnListaClientes;
    private javax.swing.JButton btnListaReportes;
    private javax.swing.JButton btnMenuGestorPrincipal;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
