/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import paneles.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import subpanelesmenu.Menu;

/**
 *
 * @author josea
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private boolean isMenuOpen = false;
    private Timer timer;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Recursos/tribal - Editado.png")).getImage());
        
        iniciarReloj();
        
        Menu panel1 = new Menu();
        panel1.setSize(1090, 670);
        panel1.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel1);
        this.contenido.revalidate();
        this.contenido.repaint();
    }
    
    private void iniciarReloj() {
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); // Configuramos el formato de fecha y hora.
        // Creamos el Timer para que se ejecute a cada segundo.
        timer = new Timer(1000, e-> { 
           //Obtenemos la fecha y hora actual.
           Date ahora = new Date();
           this.lblFecha.setText(formatoFecha.format(ahora));
        }); 
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        btnListaEmpleados = new javax.swing.JButton();
        btnEditarEmpleado = new javax.swing.JButton();
        btnBorrarEmpleado = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGenerarReportes = new javax.swing.JButton();
        btnMenuSecundario = new javax.swing.JButton();
        btnListaReportes = new javax.swing.JButton();
        btnEleminarReportes = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDesplegar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Gestor de Empresa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        menu.setBackground(new java.awt.Color(0, 0, 102));
        menu.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menus");
        menu.add(jLabel1);
        jLabel1.setBounds(100, 10, 179, 44);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menus:");
        menu.add(jLabel2);
        jLabel2.setBounds(20, 520, 160, 30);

        btnAgregarEmpleado.setBackground(new java.awt.Color(0, 0, 102));
        btnAgregarEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnAgregarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/icono agregarr empleados.png"))); // NOI18N
        btnAgregarEmpleado.setText("Agregar Empleado");
        btnAgregarEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAgregarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarEmpleadoMouseExited(evt);
            }
        });
        menu.add(btnAgregarEmpleado);
        btnAgregarEmpleado.setBounds(20, 100, 330, 38);

        btnSalir.setBackground(new java.awt.Color(0, 0, 102));
        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/exit_icon.png"))); // NOI18N
        btnSalir.setText("Salida");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        menu.add(btnSalir);
        btnSalir.setBounds(80, 730, 230, 50);

        btnMenuPrincipal.setBackground(new java.awt.Color(0, 0, 102));
        btnMenuPrincipal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/house_3637847.png"))); // NOI18N
        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuPrincipalMouseExited(evt);
            }
        });
        menu.add(btnMenuPrincipal);
        btnMenuPrincipal.setBounds(20, 560, 340, 40);

        btnListaEmpleados.setBackground(new java.awt.Color(0, 0, 102));
        btnListaEmpleados.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnListaEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnListaEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/curriculum_2726610.png"))); // NOI18N
        btnListaEmpleados.setText("Lista de Empleados");
        btnListaEmpleados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnListaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaEmpleadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaEmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaEmpleadosMouseExited(evt);
            }
        });
        menu.add(btnListaEmpleados);
        btnListaEmpleados.setBounds(20, 150, 330, 40);

        btnEditarEmpleado.setBackground(new java.awt.Color(0, 0, 102));
        btnEditarEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnEditarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/user_16470757.png"))); // NOI18N
        btnEditarEmpleado.setText("Editar Empleado");
        btnEditarEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEditarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarEmpleadoMouseExited(evt);
            }
        });
        menu.add(btnEditarEmpleado);
        btnEditarEmpleado.setBounds(20, 200, 330, 40);

        btnBorrarEmpleado.setBackground(new java.awt.Color(0, 0, 102));
        btnBorrarEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnBorrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/unemployed_7557115.png"))); // NOI18N
        btnBorrarEmpleado.setText("Borrar Empleado");
        btnBorrarEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnBorrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBorrarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBorrarEmpleadoMouseExited(evt);
            }
        });
        menu.add(btnBorrarEmpleado);
        btnBorrarEmpleado.setBounds(20, 250, 330, 40);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 19)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Empleados");
        menu.add(jLabel15);
        jLabel15.setBounds(10, 60, 160, 30);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        menu.add(jSeparator1);
        jSeparator1.setBounds(10, 510, 350, 10);

        btnGenerarReportes.setBackground(new java.awt.Color(0, 0, 102));
        btnGenerarReportes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnGenerarReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Icono Generar Reportes pequeño.png"))); // NOI18N
        btnGenerarReportes.setText("Generar Reportes");
        btnGenerarReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnGenerarReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarReportesMouseExited(evt);
            }
        });
        menu.add(btnGenerarReportes);
        btnGenerarReportes.setBounds(20, 340, 330, 40);

        btnMenuSecundario.setBackground(new java.awt.Color(0, 0, 102));
        btnMenuSecundario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnMenuSecundario.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/recruiter_4412930.png"))); // NOI18N
        btnMenuSecundario.setText("Menu Gestor de Clientes");
        btnMenuSecundario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenuSecundario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuSecundarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuSecundarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuSecundarioMouseExited(evt);
            }
        });
        menu.add(btnMenuSecundario);
        btnMenuSecundario.setBounds(20, 620, 340, 40);

        btnListaReportes.setBackground(new java.awt.Color(0, 0, 102));
        btnListaReportes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnListaReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnListaReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/ListaReportes.png"))); // NOI18N
        btnListaReportes.setText("Lista de Reportes");
        btnListaReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnListaReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaReportesMouseExited(evt);
            }
        });
        menu.add(btnListaReportes);
        btnListaReportes.setBounds(20, 390, 330, 40);

        btnEleminarReportes.setBackground(new java.awt.Color(0, 0, 102));
        btnEleminarReportes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnEleminarReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnEleminarReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/EleminarReporte(Pequeño).png"))); // NOI18N
        btnEleminarReportes.setText("Eleminar Reporte");
        btnEleminarReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEleminarReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEleminarReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEleminarReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEleminarReportesMouseExited(evt);
            }
        });
        menu.add(btnEleminarReportes);
        btnEleminarReportes.setBounds(20, 440, 330, 40);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        menu.add(jSeparator2);
        jSeparator2.setBounds(10, 300, 350, 10);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        menu.add(jSeparator3);
        jSeparator3.setBounds(10, 300, 350, 10);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 19)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Reportes");
        menu.add(jLabel17);
        jLabel17.setBounds(10, 310, 160, 30);

        jPanel3.add(menu);
        menu.setBounds(0, 0, 0, 790);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/azteca tec logo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(61, 13, 229, 204);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2- Instrucciones");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 500, 150, 30);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gestor de Empresa");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(52, 229, 265, 49);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Empresa de \"Azteca Tec\" donde podras");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 320, 329, 30);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("organizar y llevar un control en las activi-");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 350, 350, 30);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("dades y recursos que tiene la empresa.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 380, 330, 30);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("1- Acerca de");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 470, 150, 30);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Para mas informacion presiona los botones");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 430, 360, 30);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("En la seccion del menu desplegable");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 570, 310, 30);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("En la seccion del menu principal o tambien");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 540, 368, 30);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bienvenido al programa del Gestor de ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 296, 329, 30);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(0, 0, 378, 790);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(null);

        btnDesplegar.setBackground(new java.awt.Color(0, 255, 255));
        btnDesplegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/menu_2550298.png"))); // NOI18N
        btnDesplegar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnDesplegar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesplegarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDesplegarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDesplegarMouseExited(evt);
            }
        });
        jPanel2.add(btnDesplegar);
        btnDesplegar.setBounds(20, 14, 78, 71);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Menu Desplegable / Dar click en el para abri el menu desplegable");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 36, 534, 30);

        lblFecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Hora y Fecha Actual");
        jPanel2.add(lblFecha);
        lblFecha.setBounds(814, 23, 290, 40);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(810, 60, 300, 10);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(380, 0, 1110, 100);

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanel3.add(contenido);
        contenido.setBounds(390, 110, 1090, 670);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesplegarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesplegarMouseEntered
        this.btnDesplegar.setBackground(Color.green);
    }//GEN-LAST:event_btnDesplegarMouseEntered

    private void btnDesplegarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesplegarMouseExited
        this.btnDesplegar.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnDesplegarMouseExited

    private void btnDesplegarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesplegarMouseClicked
        if (isMenuOpen) {
            closeMenu();
        } else {
            openMenu();
        }
    }//GEN-LAST:event_btnDesplegarMouseClicked

    private void btnAgregarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoMouseEntered
        this.btnAgregarEmpleado.setBackground(Color.green);
    }//GEN-LAST:event_btnAgregarEmpleadoMouseEntered

    private void btnAgregarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoMouseExited
        this.btnAgregarEmpleado.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnAgregarEmpleadoMouseExited

    private void btnAgregarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoMouseClicked
        AgregarEmpleado panel1 = new AgregarEmpleado();
        panel1.setSize(1090, 670);
        panel1.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel1);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnAgregarEmpleadoMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        this.btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        this.btnSalir.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        int confirmar = JOptionPane.showConfirmDialog(null, "¿Estas seguro(a) de querer salir del programa?", "Confirmar Salida", JOptionPane.YES_NO_OPTION, 3);
        if (confirmar == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "De acuerdo le deseamos un buen dia y regrese pronto.", "Despedida", 1);
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnMenuPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuPrincipalMouseEntered
        this.btnMenuPrincipal.setBackground(Color.green);
    }//GEN-LAST:event_btnMenuPrincipalMouseEntered

    private void btnMenuPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuPrincipalMouseExited
        this.btnMenuPrincipal.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnMenuPrincipalMouseExited

    private void btnMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuPrincipalMouseClicked
        Menu p = new Menu();
        p.setSize(1090, 670);
        p.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(p);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnMenuPrincipalMouseClicked

    private void btnListaEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaEmpleadosMouseEntered
        this.btnListaEmpleados.setBackground(Color.green);
    }//GEN-LAST:event_btnListaEmpleadosMouseEntered

    private void btnListaEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaEmpleadosMouseExited
        this.btnListaEmpleados.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnListaEmpleadosMouseExited

    private void btnListaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaEmpleadosMouseClicked
        ListaEmpleados panel2 = new ListaEmpleados();
        panel2.setSize(1090, 670);
        panel2.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel2);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnListaEmpleadosMouseClicked

    private void btnEditarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarEmpleadoMouseEntered
        this.btnEditarEmpleado.setBackground(Color.green);
    }//GEN-LAST:event_btnEditarEmpleadoMouseEntered

    private void btnEditarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarEmpleadoMouseExited
        this.btnEditarEmpleado.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnEditarEmpleadoMouseExited

    private void btnEditarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarEmpleadoMouseClicked
        EditarEmpleado panel3 = new EditarEmpleado();
        panel3.setSize(1090, 670);
        panel3.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel3);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnEditarEmpleadoMouseClicked

    private void btnBorrarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarEmpleadoMouseEntered
        this.btnBorrarEmpleado.setBackground(Color.green);
    }//GEN-LAST:event_btnBorrarEmpleadoMouseEntered

    private void btnBorrarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarEmpleadoMouseExited
        this.btnBorrarEmpleado.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnBorrarEmpleadoMouseExited

    private void btnBorrarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarEmpleadoMouseClicked
        BorrarEmpleado panel4 = new BorrarEmpleado();
        panel4.setSize(1090, 670);
        panel4.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel4);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnBorrarEmpleadoMouseClicked

    private void btnGenerarReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportesMouseEntered
        this.btnGenerarReportes.setBackground(Color.green);
    }//GEN-LAST:event_btnGenerarReportesMouseEntered

    private void btnGenerarReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportesMouseExited
        this.btnGenerarReportes.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnGenerarReportesMouseExited

    private void btnGenerarReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportesMouseClicked
        GenerarReportes panel5 = new GenerarReportes();
        panel5.setSize(1090, 670);
        panel5.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel5);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnGenerarReportesMouseClicked

    private void btnMenuSecundarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuSecundarioMouseEntered
        this.btnMenuSecundario.setBackground(Color.green);
    }//GEN-LAST:event_btnMenuSecundarioMouseEntered

    private void btnMenuSecundarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuSecundarioMouseExited
        this.btnMenuSecundario.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnMenuSecundarioMouseExited

    private void btnMenuSecundarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuSecundarioMouseClicked
        MenuSecundario ventana2 = new MenuSecundario();
        ventana2.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnMenuSecundarioMouseClicked

    private void btnListaReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaReportesMouseEntered
        this.btnListaReportes.setBackground(Color.green);
    }//GEN-LAST:event_btnListaReportesMouseEntered

    private void btnListaReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaReportesMouseExited
        this.btnListaReportes.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnListaReportesMouseExited

    private void btnListaReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaReportesMouseClicked
        ListaReportes panel6 = new ListaReportes();
        panel6.setSize(1090, 670);
        panel6.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel6);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnListaReportesMouseClicked

    private void btnEleminarReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEleminarReportesMouseEntered
        this.btnEleminarReportes.setBackground(Color.green);
    }//GEN-LAST:event_btnEleminarReportesMouseEntered

    private void btnEleminarReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEleminarReportesMouseExited
        this.btnEleminarReportes.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnEleminarReportesMouseExited

    private void btnEleminarReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEleminarReportesMouseClicked
        EleminarReportes panel7 = new EleminarReportes();
        panel7.setSize(1090, 670);
        panel7.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(panel7);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnEleminarReportesMouseClicked

    private void openMenu() {
        timer = new Timer(10, new ActionListener() {
            int width = menu.getWidth();
            @Override
            public void actionPerformed(ActionEvent e) {
                if (width < 378) {
                    width += 10;
                    menu.setBounds(0, 0, width, menu.getHeight());
                } else {
                    timer.stop();
                    isMenuOpen = true;
                }
            }
        });
        timer.start();
    }
    
    private void closeMenu() {
        timer = new Timer(10, new ActionListener() {
            int width = menu.getWidth();
            @Override
            public void actionPerformed(ActionEvent e) {
                if (width > 0) {
                    width -= 10;
                    menu.setBounds(0, 0, width, menu.getHeight());
                } else {
                    timer.stop();
                    isMenuOpen = false;
                }
            }
        });
        timer.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnBorrarEmpleado;
    private javax.swing.JButton btnDesplegar;
    private javax.swing.JButton btnEditarEmpleado;
    private javax.swing.JButton btnEleminarReportes;
    private javax.swing.JButton btnGenerarReportes;
    private javax.swing.JButton btnListaEmpleados;
    private javax.swing.JButton btnListaReportes;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnMenuSecundario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
