/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import java.awt.BorderLayout;
import java.awt.Color;
import subpanelesmenu.*;

/**
 *
 * @author josea
 */
public class Actividades extends javax.swing.JPanel {

    /**
     * Creates new form AgregarActividad
     */
    public Actividades() {
        initComponents();
        
        AgregarActividad p1 = new AgregarActividad();
        p1.setSize(1090, 580);
        p1.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(p1, BorderLayout.CENTER);
        this.contenido.revalidate();
        this.contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBorrarActividad = new javax.swing.JButton();
        btnAgregarActividad = new javax.swing.JButton();
        btnListaActividades = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnEditarActividad = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Actividades");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 50, 120, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/project-management_11445887.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 20, 90, 70);

        btnBorrarActividad.setBackground(new java.awt.Color(0, 0, 153));
        btnBorrarActividad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnBorrarActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/clipboard_7249124.png"))); // NOI18N
        btnBorrarActividad.setText("Eliminar Act");
        btnBorrarActividad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnBorrarActividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarActividadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBorrarActividadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBorrarActividadMouseExited(evt);
            }
        });
        jPanel1.add(btnBorrarActividad);
        btnBorrarActividad.setBounds(870, 20, 210, 60);

        btnAgregarActividad.setBackground(new java.awt.Color(0, 0, 153));
        btnAgregarActividad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnAgregarActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/agregar act.png"))); // NOI18N
        btnAgregarActividad.setText("Agregar Act");
        btnAgregarActividad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAgregarActividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarActividadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarActividadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarActividadMouseExited(evt);
            }
        });
        jPanel1.add(btnAgregarActividad);
        btnAgregarActividad.setBounds(240, 20, 210, 60);

        btnListaActividades.setBackground(new java.awt.Color(0, 0, 153));
        btnListaActividades.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnListaActividades.setForeground(new java.awt.Color(255, 255, 255));
        btnListaActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/lista act.png"))); // NOI18N
        btnListaActividades.setText("Lista de Act");
        btnListaActividades.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnListaActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaActividadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaActividadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaActividadesMouseExited(evt);
            }
        });
        jPanel1.add(btnListaActividades);
        btnListaActividades.setBounds(450, 20, 210, 60);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestion de");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 20, 120, 30);

        btnEditarActividad.setBackground(new java.awt.Color(0, 0, 153));
        btnEditarActividad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnEditarActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/editar act.png"))); // NOI18N
        btnEditarActividad.setText("Editar Act");
        btnEditarActividad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEditarActividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarActividadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarActividadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarActividadMouseExited(evt);
            }
        });
        jPanel1.add(btnEditarActividad);
        btnEditarActividad.setBounds(660, 20, 210, 60);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 110));

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1090, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActividadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarActividadMouseEntered
        this.btnBorrarActividad.setBackground(Color.green);
    }//GEN-LAST:event_btnBorrarActividadMouseEntered

    private void btnBorrarActividadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarActividadMouseExited
        this.btnBorrarActividad.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnBorrarActividadMouseExited

    private void btnBorrarActividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarActividadMouseClicked
        BorrarActividad p4 = new BorrarActividad();
        p4.setSize(1090, 580);
        p4.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(p4, BorderLayout.CENTER);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnBorrarActividadMouseClicked

    private void btnAgregarActividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarActividadMouseClicked
        AgregarActividad p1 = new AgregarActividad();
        p1.setSize(1090, 580);
        p1.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(p1, BorderLayout.CENTER);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnAgregarActividadMouseClicked

    private void btnAgregarActividadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarActividadMouseEntered
        this.btnAgregarActividad.setBackground(Color.green);
    }//GEN-LAST:event_btnAgregarActividadMouseEntered

    private void btnAgregarActividadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarActividadMouseExited
        this.btnAgregarActividad.setBackground(new Color(0, 0, 153));
        
    }//GEN-LAST:event_btnAgregarActividadMouseExited

    private void btnListaActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaActividadesMouseClicked
        ListaActividades p2 = new ListaActividades();
        p2.setSize(1090, 580);
        p2.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(p2, BorderLayout.CENTER);
        this.contenido.revalidate();
        this.contenido.repaint();
        
    }//GEN-LAST:event_btnListaActividadesMouseClicked

    private void btnListaActividadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaActividadesMouseEntered
        this.btnListaActividades.setBackground(Color.green);
    }//GEN-LAST:event_btnListaActividadesMouseEntered

    private void btnListaActividadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaActividadesMouseExited
        this.btnListaActividades.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnListaActividadesMouseExited

    private void btnEditarActividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarActividadMouseClicked
        EditarActividad p3 = new EditarActividad();
        p3.setSize(1090, 580);
        p3.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(p3, BorderLayout.CENTER);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnEditarActividadMouseClicked

    private void btnEditarActividadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarActividadMouseEntered
        this.btnEditarActividad.setBackground(Color.green);
    }//GEN-LAST:event_btnEditarActividadMouseEntered

    private void btnEditarActividadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarActividadMouseExited
        this.btnEditarActividad.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnEditarActividadMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarActividad;
    private javax.swing.JButton btnBorrarActividad;
    private javax.swing.JButton btnEditarActividad;
    private javax.swing.JButton btnListaActividades;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
