/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import Objeto.Clientes;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author josea
 */
public class AgregarCliente extends javax.swing.JPanel {

    /**
     * Creates new form AgregarCliente
     */
    public AgregarCliente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFechaRegistro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboEstatus = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Agregar Cliente.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 140, 130);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar Cliente a la Empresa.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 50, 780, 70);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 170));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 21)); // NOI18N
        jLabel4.setText("Rellena todos los espacios para agregar los datos del cliente.");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 660, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel5.setText("Direccion del Cliente:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 190, 190, 30);

        txtNombres.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel2.add(txtNombres);
        txtNombres.setBounds(720, 80, 250, 30);

        txtDireccion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel2.add(txtDireccion);
        txtDireccion.setBounds(190, 190, 310, 30);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel6.setText("Apellido:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(280, 80, 90, 30);

        txtEmail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel2.add(txtEmail);
        txtEmail.setBounds(720, 140, 240, 30);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel7.setText("ID del Cliente:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 80, 120, 30);

        txtId.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel2.add(txtId);
        txtId.setBounds(130, 80, 130, 30);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel8.setText("Nombres:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(630, 80, 90, 30);

        txtApellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel2.add(txtApellido);
        txtApellido.setBounds(360, 80, 250, 30);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel9.setText("Telefono:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(340, 140, 90, 30);

        txtTelefono.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel2.add(txtTelefono);
        txtTelefono.setBounds(420, 140, 220, 30);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel10.setText("Fecha de Registro:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 140, 160, 30);

        txtFechaRegistro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jPanel2.add(txtFechaRegistro);
        txtFechaRegistro.setBounds(170, 140, 150, 30);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel11.setText("Email:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(660, 140, 90, 30);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel12.setText("Estatus del Cliente:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(510, 190, 160, 30);

        cboEstatus.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        cboEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona un Estatus --", "-- Activo --", "-- Inactivo --" }));
        jPanel2.add(cboEstatus);
        cboEstatus.setBounds(670, 190, 260, 30);

        btnGuardar.setBackground(new java.awt.Color(0, 0, 153));
        btnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 21)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/Agregar Cliente.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        jPanel2.add(btnGuardar);
        btnGuardar.setBounds(220, 260, 480, 130);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1090, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        this.btnGuardar.setBackground(Color.green);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        this.btnGuardar.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        if (validarFormulario())
            guardarCliente();
        
    }//GEN-LAST:event_btnGuardarMouseClicked

    private boolean validarTextField(JTextField textField, String mensaje) {
         if (textField.getText().trim().isEmpty()) {
             JOptionPane.showMessageDialog(null, mensaje);
             textField.requestFocus();
             return false;
         }
         return true;
    }
    
    private boolean validarComboBox(JComboBox<String> comboBox, String mensaje) {
        if (comboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, mensaje);
            comboBox.requestFocus();
            return false;
        }
        return true;
    }
    
    private boolean validarFormulario() {
        if (!validarTextField(this.txtId, "El campo ID del Cliente esta vacio.")) return false;
        if (!validarTextField(this.txtApellido, "El campo Apellido esta vacio.")) return false;
        if (!validarTextField(this.txtNombres, "El campo Nombres esta vacio")) return false;
        if (!validarTextField(this.txtFechaRegistro, "El campo Fecha de Contrato esta vacio.")) return false;
        if (!validarTextField(this.txtTelefono, "El campo Telefono esta vacio")) return false;
        if (!validarTextField(this.txtEmail, "El campo Email esta vacio.")) return false;
        if (!validarTextField(this.txtDireccion, "El campo Direccion esta vacio")) return false;
        
        if (!validarComboBox(this.cboEstatus, "No has seleccionado el Estatus del Cliente.")) return false;
        
        return true;
    }
    
    private void guardarCliente() {
        if (!validarFecha(this.txtFechaRegistro.getText())) {
            return;
        }
        
        if (!validarTelefono()) {
            return;
        }
        
        if (!validarEmail()) {
            return;
        }
        
        try {
            Clientes cliente = new Clientes(this.txtId.getText(), this.txtApellido.getText(), this.txtNombres.getText(), this.txtFechaRegistro.getText(),
                    this.txtTelefono.getText(), this.txtEmail.getText(), this.txtDireccion.getText(), this.cboEstatus.getSelectedItem().toString());
            try (BufferedWriter bw = new BufferedWriter(new FileWriter("clientes.txt", true))) {
                bw.write(cliente.toString());
                bw.newLine();
            }
            JOptionPane.showMessageDialog(null, "Cliente agrgeado correctamente.", "Exito.", 1);
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar: " + e.getMessage(), "ERROR", 0);
        }
    }
    
    private boolean validarFecha(String fechaRegsitro) {
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        formatoFecha.setLenient(false);
        
        try {
            formatoFecha.parse(fechaRegsitro);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "La Fecha de Registro tiene un formato incorrecto. \n El formato"
                    + "correcto es dd/MM/yyyy.", "ADVERTENCIA: Error de Formato.", 2);
            this.txtFechaRegistro.requestFocus();
            return false;
        }
        return true;
    }
    
    private boolean validarTelefono() {
        String telefono = this.txtTelefono.getText();
        // Expresion regurlar del formato 011 52 xx xxxx-xxxx.
        String regex = "^011 52 \\d{2} \\d{4}-\\d{4}$";
        
        if (!telefono.matches(regex)) {
            JOptionPane.showMessageDialog(null, "El formato de Telefono es invalido. \nEl formato esperado es: 011 52 xx xxxx-xxxx", "ADVERTENCIA: Error de Formato", 2);
            this.txtTelefono.requestFocus();
            return false;
        }
        return true;
    }
    
    private boolean validarEmail() {
        String email = this.txtEmail.getText();
        String regex = "^[\\w._%+-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";
        
        if (!email.matches(regex)) {
            JOptionPane.showMessageDialog(null, "El formato de Email es invalido. \nEl formato correcto es: nombredeusuario@dominio.com", "ADVERTENCIA: Error de formato", 2);
            this.txtEmail.requestFocus();
            return false;
        }
        return true;
    }
    
    private void limpiarCampos() {
        this.txtId.setText(null);
        this.txtApellido.setText(null);
        this.txtNombres.setText(null);
        this.txtFechaRegistro.setText(null);
        this.txtTelefono.setText(null);
        this.txtEmail.setText(null);
        this.txtDireccion.setText(null);
        this.cboEstatus.setSelectedItem("-- Selecciona un Estatus --");
    }
    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboEstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
