/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import Objeto.ReportesClientes;
import Objeto.ReportesActividades;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author josea
 */
public class BorrarReporte extends javax.swing.JPanel {

    /**
     * Creates new form BorrarReporte
     */
    public BorrarReporte() {
        initComponents();
        cargarReportesCliente();
        cargarReportesActividad();
    }
    
    private void cargarReportesCliente() {
        String[] reportes = ReportesClientes.listaReportes();
        this.cboReportesCliente.removeAllItems();
        
        this.cboReportesCliente.addItem("-- Seleccione un Reporte --");
        for (String reporte : reportes) {
            this.cboReportesCliente.addItem(reporte);
        }
    }
    
    private void cargarReportesActividad() {
        String[] reportes = ReportesActividades.listaReportes();
        this.cboReportesActividad.removeAllItems();
        
        this.cboReportesActividad.addItem("-- Selecciona un Reporte --");
        for (String reporte : reportes) {
            this.cboReportesActividad.addItem(reporte);
        }
    }
    
    private void borrarReporteClientes() {
        String reporteSeleccionado = (String) this.cboReportesCliente.getSelectedItem();
        if ("-- Seleccione un Reporte --".equals(reporteSeleccionado)) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un reporte para eliminarlo.", "ADVERTENCIA: No hay seleccion de reporte.", 2);
            this.cboReportesCliente.requestFocus();
            return; 
        }
        
        if (ReportesClientes.eliminarReportes(reporteSeleccionado)) {
            JOptionPane.showMessageDialog(null, "Reporte eliminado correctamente.", "Exito", 1);
            cargarReportesCliente();
        } else {
            JOptionPane.showMessageDialog(null, "Error al eleminar el reporte.", "ERROR", 0);
        }
    }
    
    private void borrarReporteActividad() {
        String reporteSeleccionado = (String) this.cboReportesActividad.getSelectedItem();
        if ("-- Selecciona un Reporte --".equals(reporteSeleccionado)) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un reporte para eliminarlo.", "ADVERTENCIA: No hay seleccion de reporte.", 2);
            this.cboReportesActividad.requestFocus();
            return; 
        }
        
        if (ReportesActividades.eliminarReporte(reporteSeleccionado)) {
            JOptionPane.showMessageDialog(null, "Reporte eliminado correctamente.", "Exito", 1);
            cargarReportesActividad();
        } else {
            JOptionPane.showMessageDialog(null, "Error al eleminar el reporte.", "ERROR", 0);
        }
    }

    /**
     * This method is called fromA within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboReportesActividad = new javax.swing.JComboBox<>();
        cboReportesCliente = new javax.swing.JComboBox<>();
        btnEliminarReporteAct = new javax.swing.JButton();
        btnEliminarReporteCliente = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/close_6730401.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 130, 120);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Eliminar Reporte de la lista");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 50, 710, 50);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(550, 10, 30, 510);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel3.setText("Selecciona un reporte en el siguiente  Combo Box para poder guardarlo:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(560, 70, 530, 30);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel4.setText("Selecciona un reporte en el siguiente  Combo Box para poder guardarlo:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 70, 530, 30);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 21)); // NOI18N
        jLabel5.setText("Actividades");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(740, 20, 140, 50);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 21)); // NOI18N
        jLabel6.setText("Clientes");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(190, 10, 100, 50);

        cboReportesActividad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        cboReportesActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboReportesActividad);
        cboReportesActividad.setBounds(620, 110, 360, 40);

        cboReportesCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        cboReportesCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboReportesCliente);
        cboReportesCliente.setBounds(70, 110, 360, 40);

        btnEliminarReporteAct.setBackground(new java.awt.Color(0, 0, 153));
        btnEliminarReporteAct.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 21)); // NOI18N
        btnEliminarReporteAct.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarReporteAct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/close_6730401.png"))); // NOI18N
        btnEliminarReporteAct.setText("Eliminar Reporte");
        btnEliminarReporteAct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEliminarReporteAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarReporteActMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarReporteActMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarReporteActMouseExited(evt);
            }
        });
        jPanel2.add(btnEliminarReporteAct);
        btnEliminarReporteAct.setBounds(580, 250, 460, 140);

        btnEliminarReporteCliente.setBackground(new java.awt.Color(0, 0, 153));
        btnEliminarReporteCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 21)); // NOI18N
        btnEliminarReporteCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarReporteCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/close_6730401.png"))); // NOI18N
        btnEliminarReporteCliente.setText("Eliminar Reporte");
        btnEliminarReporteCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEliminarReporteCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarReporteClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarReporteClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarReporteClienteMouseExited(evt);
            }
        });
        jPanel2.add(btnEliminarReporteCliente);
        btnEliminarReporteCliente.setBounds(30, 250, 460, 140);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1090, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarReporteClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarReporteClienteMouseEntered
        this.btnEliminarReporteCliente.setBackground(Color.red);
    }//GEN-LAST:event_btnEliminarReporteClienteMouseEntered

    private void btnEliminarReporteClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarReporteClienteMouseExited
        this.btnEliminarReporteCliente.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnEliminarReporteClienteMouseExited

    private void btnEliminarReporteClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarReporteClienteMouseClicked
        borrarReporteClientes();
    }//GEN-LAST:event_btnEliminarReporteClienteMouseClicked

    private void btnEliminarReporteActMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarReporteActMouseEntered
        this.btnEliminarReporteAct.setBackground(Color.red);
    }//GEN-LAST:event_btnEliminarReporteActMouseEntered

    private void btnEliminarReporteActMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarReporteActMouseExited
        this.btnEliminarReporteAct.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnEliminarReporteActMouseExited

    private void btnEliminarReporteActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarReporteActMouseClicked
        borrarReporteActividad();
    }//GEN-LAST:event_btnEliminarReporteActMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarReporteAct;
    private javax.swing.JButton btnEliminarReporteCliente;
    private javax.swing.JComboBox<String> cboReportesActividad;
    private javax.swing.JComboBox<String> cboReportesCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
