/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import javax.swing.table.DefaultTableModel;
import ClasesUtilitarias.ArchivoUtilEmpleados;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author josea
 */
public class BorrarEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form BorrarEmpleado
     */
    public BorrarEmpleado() {
        initComponents();
        cargarIDs();
        cargarColumnasTabla();
    }
    
    private void cargarColumnasTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Apellio", "Nombres", "F. Nacimiento", "F. Contrato", "CURP"});
        
        this.tblEmpleado.setModel(modelo);
    }
    
    private void cargarIDs() {
        this.cboIDs.removeAllItems(); // Primero Limpia el combo box XD
        this.cboIDs.addItem("-- Selecciona un ID --"); // Opcion predeterminada
        
        List<String[]> datos = ArchivoUtilEmpleados.leerArchivo("empleados.txt");
        for (String[] fila : datos) 
            this.cboIDs.addItem(fila[0]); // Solo agrega el datos de los IDs
    }
    
    private void cargarDatosEmpleado() {
        if (this.cboIDs.getSelectedIndex() <= 0) {
            limpiarTabla();
            JOptionPane.showMessageDialog(null, "Debe seleccionar un ID valido.", "ADVERTENCIA: Escoge un ID", 2);
            return;
        }
        
        String idSeleccionado = (String) this.cboIDs.getSelectedItem();
        List<String[]> datos = ArchivoUtilEmpleados.leerArchivo("empleados.txt");
        limpiarTabla();
        
        for (String[] fila : datos) {
            if (fila[0].equals(idSeleccionado)) {
                DefaultTableModel model = (DefaultTableModel) this.tblEmpleado.getModel();
                
                model.addRow(new Object[]{fila[1], fila[2] , fila[3], fila[4], fila[5]}); // Datos que son apellido, nombres, fecha de nacimiento de contrato y CURP
                break;
            }
        }
    }
    
    private void limpiarTabla() {
        DefaultTableModel model = (DefaultTableModel) this.tblEmpleado.getModel();
        model.setRowCount(0);
    }
    
    private void eliminarEmpleado() {
        if (this.cboIDs.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un ID para eliminar.", "ADVERTENCIA: Escoge un ID", 2);
            return;
        }
        
        String idSeleccionado = (String) this.cboIDs.getSelectedItem();
        List<String[]> datos = ArchivoUtilEmpleados.leerArchivo("empleados.txt");
        boolean encontrado = false;
        // Eliminanos al empleado con el ID seleccionado.
        for (int i = 0; i < datos.size(); i++) {
            if (datos.get(i)[0].equals(idSeleccionado)) {
                datos.remove(i);
                encontrado = true;
                break;
            }
        }
        
        if (encontrado) {
            ArchivoUtilEmpleados.escribirArchivo("empleados.txt", datos);
            JOptionPane.showMessageDialog(null, "Empleado eliminado correctamente.", "Exito", 1);
            limpiarTabla();
            cargarIDs(); // El combo box se actualizara cada vez que borremos a un empleado XD.
        } else {
            JOptionPane.showMessageDialog(null, "No se encontro el empleado con el ID seleccionado.", "ERROR: ID no encontrado", 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboIDs = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEleminar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Borrar Empleado de la Empresa.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 40, 840, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/employee_4333851.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 150, 120);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel3.setText("Datos del ID seleccionado.");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(840, 150, 230, 40);

        cboIDs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIDsActionPerformed(evt);
            }
        });
        jPanel2.add(cboIDs);
        cboIDs.setBounds(760, 10, 310, 40);

        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmpleado.setRowHeight(25);
        jScrollPane1.setViewportView(tblEmpleado);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 810, 110);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel4.setText("Selecciona un ID en el siguiente Combo Box para poder eleminarlo:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 770, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel5.setText("Al seleccionar un ID apareceran los datos aqui en esta tabla:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 230, 710, 40);

        btnEleminar.setBackground(new java.awt.Color(0, 0, 102));
        btnEleminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        btnEleminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEleminar.setText("Eleminar Empleado");
        btnEleminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEleminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEleminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEleminarMouseExited(evt);
            }
        });
        jPanel2.add(btnEleminar);
        btnEleminar.setBounds(270, 330, 520, 100);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1090, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEleminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEleminarMouseEntered
        this.btnEleminar.setBackground(Color.red);
    }//GEN-LAST:event_btnEleminarMouseEntered

    private void btnEleminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEleminarMouseExited
        this.btnEleminar.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnEleminarMouseExited

    private void btnEleminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEleminarMouseClicked
        eliminarEmpleado();
    }//GEN-LAST:event_btnEleminarMouseClicked

    private void cboIDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIDsActionPerformed
        cargarDatosEmpleado();
    }//GEN-LAST:event_cboIDsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEleminar;
    private javax.swing.JComboBox<String> cboIDs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpleado;
    // End of variables declaration//GEN-END:variables
}
