/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import ClasesUtilitarias.ArchivoUtilClientes;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author josea
 */
public class BorrarCliente extends javax.swing.JPanel {

    /**
     * Creates new form BorrarCliente
     */
    public BorrarCliente() {
        initComponents();
        cargarIDs();
        cargarColummnasTabla();
    }
    
    private void cargarColummnasTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Apellio", "Nombres", "F. Registro", "Telefono", "Email"});
        
        this.tblCliente.setModel(modelo);
    }
    
    private void cargarIDs() {
        this.cboIDs.removeAllItems();
        this.cboIDs.addItem("-- Selecciona un ID --");
        
        List<String[]> datos = ArchivoUtilClientes.leerArchivo("clientes.txt");
        for (String[] fila : datos) 
            this.cboIDs.addItem(fila[0]);
    }
    
    private void cargarDatosCliente() {
        if (this.cboIDs.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Selecciona un ID para borrar.", "ADVERTENCIA", 2);
            return;
        }
        
        String idSeleccionado = (String) this.cboIDs.getSelectedItem();
        List<String[]> datos = ArchivoUtilClientes.leerArchivo("clientes.txt");
        limpiarTabla();
        
        for (String[] fila : datos) {
            if (fila[0].equals(idSeleccionado)) {
                DefaultTableModel model = (DefaultTableModel) this.tblCliente.getModel();
                
                model.addRow(new Object[]{fila[1], fila[2], fila[3], fila[4], fila[5]});
                break;
            }
        }
    }
    
    private void limpiarTabla() {
        DefaultTableModel model = (DefaultTableModel) this.tblCliente.getModel();
        model.setRowCount(0);
    }
    
    private void eliminarCliente() {
        if (this.cboIDs.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Selecciona un ID para borrar a un cliente.", "ADVERTENCIA: No hay un ID seleccionado", 2);
            return;
        }
        
        String idSeleccionado = (String) this.cboIDs.getSelectedItem();
        List<String[]> datos = ArchivoUtilClientes.leerArchivo("clientes.txt");
        boolean encontrado = false;
        
        for (int i = 0; i < datos.size(); i++) {
            if (datos.get(i)[0].equals(idSeleccionado)) {
                datos.remove(i);
                encontrado = true;
                break;
            }
        }
        
        if (encontrado) {
            ArchivoUtilClientes.escribirArchivo("clientes.txt", datos);
            JOptionPane.showMessageDialog(null, "Cliente Eliminado correctamente.", "Exito", 1);
            limpiarTabla();
            cargarIDs();
        } else {
            JOptionPane.showMessageDialog(null, "No se encontro el cliente con el ID seleccionado.", "ERROR: ID no Encontrado", 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboIDs = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Borrar Cliente de la Empresa.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 50, 760, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/delete_10884542.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 120, 110);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel3.setText("Al seleccionar un ID apareceran los datos aqui en esta tabla:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 250, 740, 40);

        cboIDs.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        cboIDs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIDsActionPerformed(evt);
            }
        });
        jPanel2.add(cboIDs);
        cboIDs.setBounds(720, 20, 350, 40);

        tblCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCliente.setRowHeight(30);
        jScrollPane1.setViewportView(tblCliente);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 680, 150);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel4.setText("Selecciona un ID en el Combo Box para Borrar un Cliente:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 20, 690, 40);

        btnEliminar.setBackground(new java.awt.Color(0, 0, 153));
        btnEliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        jPanel2.add(btnEliminar);
        btnEliminar.setBounds(780, 140, 230, 70);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1090, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        this.btnEliminar.setBackground(Color.red);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        this.btnEliminar.setBackground(new Color(0, 0, 153));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        eliminarCliente();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void cboIDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIDsActionPerformed
        cargarDatosCliente();
    }//GEN-LAST:event_cboIDsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cboIDs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables
}
