/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import java.awt.Color;
import Objeto.Reportes;
import javax.swing.JOptionPane;

/**
 *
 * @author josea
 */
public class EleminarReportes extends javax.swing.JPanel {

    /**
     * Creates new form EleminarReportes
     */
    public EleminarReportes() {
        initComponents();
        cargarReportes();
    }
    
    private void cargarReportes() {
        String[] reportes = Reportes.listaReportes();
        this.cboReportes.removeAllItems();
        
        this.cboReportes.addItem("-- Seleccione un Reporte --");
        for ( String reporte : reportes) 
            this.cboReportes.addItem(reporte);
    }
    
    private void eleminarReportes() {
        String reporteSeleccionado = (String) this.cboReportes.getSelectedItem();
        if ("-- Seleccione un Reporte --".equals(reporteSeleccionado)) {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar un Reporte para Eleminar.", "ADVERTENCIA: Falta elegir un reporte", 2);
            return;
        }
        
        if (Reportes.eliminarReportes(reporteSeleccionado)) {
            JOptionPane.showMessageDialog(null, "Reporte eliminado correctamente.", "Exito", 1);
            cargarReportes();
        } else {
            JOptionPane.showMessageDialog(null, "Error al eleminar el reporte.", "ERROR", 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboReportes = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eleminar Reportes Creados.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 780, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/close_6730401.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 12, 140, 128);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel3.setText("Selecciona un tipo de reporte en el siguiente combo boc para eleminarlo:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 720, 40);

        cboReportes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        cboReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboReportes);
        cboReportes.setBounds(730, 10, 340, 40);

        btnEliminar.setBackground(new java.awt.Color(0, 0, 102));
        btnEliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/close_6730401.png"))); // NOI18N
        btnEliminar.setText("Eliminar Reporte");
        btnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        jPanel2.add(btnEliminar);
        btnEliminar.setBounds(80, 130, 640, 130);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1090, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        this.btnEliminar.setBackground(Color.red);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        this.btnEliminar.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        eleminarReportes();
    }//GEN-LAST:event_btnEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cboReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
