/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import com.itextpdf.text.pdf.PdfName;
import java.awt.BorderLayout;
import java.awt.Color;
import subpanelesmenu.ListaReportesActividades;
import subpanelesmenu.ListaReportesClientes;
/**
 *
 * @author josea
 */
public class ListaReportes2 extends javax.swing.JPanel {

    /**
     * Creates new form ListaReportes2
     */
    public ListaReportes2() {
        initComponents();
        
        ListaReportesClientes p1 = new ListaReportesClientes();
        p1.setSize(1090, 530);
        p1.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(p1, BorderLayout.CENTER);
        this.contenido.revalidate();
        this.contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnActividad = new javax.swing.JButton();
        bthCliente = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recursos/survey_9104313.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 128, 120);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de Reportes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 40, 460, 50);

        btnActividad.setBackground(new java.awt.Color(0, 153, 153));
        btnActividad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnActividad.setText("Actividad");
        btnActividad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnActividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActividadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActividadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActividadMouseExited(evt);
            }
        });
        jPanel1.add(btnActividad);
        btnActividad.setBounds(870, 10, 210, 120);

        bthCliente.setBackground(new java.awt.Color(0, 153, 153));
        bthCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        bthCliente.setForeground(new java.awt.Color(255, 255, 255));
        bthCliente.setText("Cliente");
        bthCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bthCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bthClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bthClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bthClienteMouseExited(evt);
            }
        });
        jPanel1.add(bthCliente);
        bthCliente.setBounds(640, 10, 210, 120);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 140));

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1090, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void bthClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bthClienteMouseEntered
        this.bthCliente.setBackground(Color.green);
    }//GEN-LAST:event_bthClienteMouseEntered

    private void bthClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bthClienteMouseExited
        this.bthCliente.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_bthClienteMouseExited

    private void bthClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bthClienteMouseClicked
        ListaReportesClientes p1 = new ListaReportesClientes();
        p1.setSize(1090, 530);
        p1.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(p1, BorderLayout.CENTER);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_bthClienteMouseClicked

    private void btnActividadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadMouseEntered
        this.btnActividad.setBackground(Color.green);
    }//GEN-LAST:event_btnActividadMouseEntered

    private void btnActividadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadMouseExited
        this.btnActividad.setBackground(new Color(0,153, 153));
    }//GEN-LAST:event_btnActividadMouseExited

    private void btnActividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadMouseClicked
        ListaReportesActividades p2 = new ListaReportesActividades();
        p2.setSize(1090, 530);
        p2.setLocation(0, 0);
        
        this.contenido.removeAll();
        this.contenido.add(p2, BorderLayout.CENTER);
        this.contenido.revalidate();
        this.contenido.repaint();
    }//GEN-LAST:event_btnActividadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthCliente;
    private javax.swing.JButton btnActividad;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
